//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DVTAnalyticsData : NSObject
{
    NSString *_platform;
    NSString *_isBeta;
}

@property(retain, nonatomic) NSString *isBeta; // @synthesize isBeta=_isBeta;
- (void).cxx_destruct;
@property(retain) NSString *platform; // @synthesize platform=_platform;

@end

