//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDELanguageSupportUI/IDESourceLanguageServiceSwiftDiagnosticItems-Protocol.h>

@class NSArray;

@interface IDESourceLanguageServiceSwiftDiagnosticItems : NSObject <IDESourceLanguageServiceSwiftDiagnosticItems>
{
    NSArray *_diagnosticItems;
    unsigned long long _diagnosticLevel;
}

@property(readonly) unsigned long long diagnosticLevel; // @synthesize diagnosticLevel=_diagnosticLevel;
@property(readonly, copy) NSArray *diagnosticItems; // @synthesize diagnosticItems=_diagnosticItems;
- (void).cxx_destruct;
- (id)initWithDiagnosticItems:(id)arg1 level:(unsigned long long)arg2;

@end

