//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class IDEActivityPopUpContentLayerController;

@protocol IDEActivityPopUpContentLayerControllerDelegate <NSObject>

@optional
- (void)popUpContentLayerController:(IDEActivityPopUpContentLayerController *)arg1 didChangePreferredHeightTo:(double)arg2;
- (void)popUpContentLayerController:(IDEActivityPopUpContentLayerController *)arg1 displayedReportCountDidChangeTo:(unsigned long long)arg2;
- (void)doneButtonWasClickedInPopUpContentLayerController:(IDEActivityPopUpContentLayerController *)arg1;
@end

