//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class IDEComparisonEditor, IDEComparisonEditorChangesStepperView, IDEComparisonEditorTimelineNavBar, IDEPathControl;

@interface IDEComparisonNavTimelineBar : IDEViewController
{
    IDEComparisonEditorTimelineNavBar *_navTimelineBarContainerView;
    IDEComparisonEditor *_comparisonEditor;
}

@property(retain) IDEComparisonEditor *comparisonEditor; // @synthesize comparisonEditor=_comparisonEditor;
@property(retain) IDEComparisonEditorTimelineNavBar *navTimelineBarContainerView; // @synthesize navTimelineBarContainerView=_navTimelineBarContainerView;
- (void).cxx_destruct;
- (void)layoutContainerView;
@property(readonly) IDEComparisonEditorChangesStepperView *changesStepperControl;
@property(readonly) IDEPathControl *secondaryPathControl;
@property(readonly) IDEPathControl *primaryPathControl;
@property BOOL hideSecondaryPathControl;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)loadView;
- (id)initWithComparisonEditor:(id)arg1;

@end

