//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEDistributionOptionViewControllerConfiguration : NSObject
{
    double _controlWidth;
    double _controlLeadingAmount;
}

@property(nonatomic) double controlLeadingAmount; // @synthesize controlLeadingAmount=_controlLeadingAmount;
@property(nonatomic) double controlWidth; // @synthesize controlWidth=_controlWidth;

@end

