//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface IDEJumpToField : NSTextField
{
}

+ (Class)cellClass;
@property BOOL showLink;
- (void)mouseDown:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)willRemoveSubview:(id)arg1;
- (void)didAddSubview:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setCell:(id)arg1;

@end

