//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTMarkup/_TtC9DVTMarkup25ContainerContentBlockView.h>

__attribute__((visibility("hidden")))
@interface _TtC9DVTMarkup11CalloutView : _TtC9DVTMarkup25ContainerContentBlockView
{
    // Error parsing type: , name: annotation
    // Error parsing type: , name: gutterView
}

- (CDUnknownBlockType).cxx_destruct;
- (void)performRendererLayout;
@property(nonatomic, readonly) double leftPadding;
@property(nonatomic, readonly) double bottomPadding;
@property(nonatomic, readonly) double topPadding;
- (id)initWithCoder:(id)arg1;

@end

