//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTMarkup/_TtC9DVTMarkup32PlaygroundMarkupContentBlockView.h>

__attribute__((visibility("hidden")))
@interface _TtC9DVTMarkup18HorizontalRuleView : _TtC9DVTMarkup32PlaygroundMarkupContentBlockView
{
}

- (id)initWithCoder:(id)arg1;
- (double)preferredHeightForWidth:(double)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

