//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <DVTMarkup/DVTMarkup.ContainerContentBlockView.h>

@interface DVTMarkup.PlaygroundMarkupRootView : DVTMarkup.ContainerContentBlockView
{
    // Error parsing type: , name: style
}

- (CDUnknownBlockType).cxx_destruct;
- (void)handleLink:(id)arg1 tappedRect:(struct CGRect)arg2 in:(id)arg3;
- (void)updateViewFromStyle;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic, readonly) double leftPadding;
- (id)initWithCoder:(id)arg1;

@end

