//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _IBLayoutGuideUpdater : NSObject
{
}

+ (void)createAndRemoveLayersForGuides:(id)arg1 existingGuideLayers:(id)arg2 creatingLayerUsingBlock:(CDUnknownBlockType)arg3;

@end

