//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSSet;

@interface IBAnnotationDocumentData : NSObject
{
    NSSet *_annotations;
    NSDate *_dateCached;
}

@property(readonly) NSDate *dateCached; // @synthesize dateCached=_dateCached;
@property(readonly) NSSet *annotations; // @synthesize annotations=_annotations;
- (void).cxx_destruct;
- (id)initWithAnnotations:(id)arg1;

@end

