//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAutolayoutFrameDecider.h>

@interface IBAutolayoutConstraintAdditionFrameDecider : IBAutolayoutFrameDecider
{
}

+ (void)decideAndSetFramesOfEntireViewHierarchyByAddingConstraints:(id)arg1 mutuallyExclusiveConstraintBreakageStrategy:(unsigned long long)arg2 replacingConstraints:(id)arg3 returningConstraintsAdded:(id *)arg4 returningConstraintsRemoved:(id *)arg5 layoutInfo:(id)arg6 delegate:(id)arg7;
+ (id)frameDeciderForAddingConstraints:(id)arg1 andReplacingConstraints:(id)arg2 layoutInfo:(id)arg3 delegate:(id)arg4;

@end

