//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEEditorDocument.h>

#import <IDEInterfaceBuilderKit/IBICActivityReportingDelegate-Protocol.h>
#import <IDEInterfaceBuilderKit/IBICCatalogItemObserver-Protocol.h>
#import <IDEInterfaceBuilderKit/IBICCatalogSynchronizerDelegate-Protocol.h>
#import <IDEInterfaceBuilderKit/IDEDocumentStructureProviding-Protocol.h>
#import <IDEInterfaceBuilderKit/IDENavigableItemArchivableRepresentationSupport-Protocol.h>

@class DVTDelayedInvocation, IBFileBuildSettingsSnapshot, IBICAbstractCatalog, IBICCatalogMutator, IBICCatalogSynchronizer, IBICPasteboardManager, IBICTransientUIStateRepository, IBMutableIdentityDictionary, NSArray, NSMutableOrderedSet, NSMutableSet, NSSet, NSString;
@protocol IBInvalidation;

@interface IBICAbstractCatalogDocument : IDEEditorDocument <IDEDocumentStructureProviding, IDENavigableItemArchivableRepresentationSupport, IBICCatalogItemObserver, IBICCatalogSynchronizerDelegate, IBICActivityReportingDelegate>
{
    NSMutableSet *_imageCatalogDocumentEditors;
    IBMutableIdentityDictionary *_editorsToWorkspaceDocuments;
    id <IBInvalidation> _catalogObservationToken;
    IBICCatalogMutator *_activeMutator;
    IBICAbstractCatalog *_unsynchronizedCatalog;
    DVTDelayedInvocation *_issueValidator;
    NSArray *_importingFileRefs;
    BOOL _replacingContent;
    BOOL _startedVerifications;
    IBMutableIdentityDictionary *_issuesByCatalogItem;
    NSSet *_cachedActivityReporters;
    NSMutableOrderedSet *_itemsWithActivity;
    NSArray *_ideTopLevelStructureObjects;
    IBICPasteboardManager *_pasteboardManager;
    IBICCatalogSynchronizer *_synchronizer;
    IBICTransientUIStateRepository *_transientUIStateRepository;
    NSSet *_defaultDeviceSpecificImageRepSlots;
    NSArray *_issues;
}

+ (id)issueBadgeForIssues:(id)arg1 ofSize:(double)arg2;
+ (long long)highestIssuesSeverityForIssues:(id)arg1;
+ (id)keyPathsForValuesAffectingIbInspectedCompressionType;
+ (BOOL)shouldTrackFileSystemChanges;
+ (BOOL)autosavesDrafts;
+ (BOOL)autosavesInPlace;
+ (id)documentForCatalogPath:(id)arg1;
+ (id)documentForCatalog:(id)arg1;
+ (void)unregisterOpenDocument:(id)arg1;
+ (void)registerOpenDocument:(id)arg1;
+ (id)openDocuments;
@property(readonly, nonatomic) NSArray *issues; // @synthesize issues=_issues;
@property(readonly, nonatomic) NSSet *defaultDeviceSpecificImageRepSlots; // @synthesize defaultDeviceSpecificImageRepSlots=_defaultDeviceSpecificImageRepSlots;
@property(readonly, nonatomic) IBICTransientUIStateRepository *transientUIStateRepository; // @synthesize transientUIStateRepository=_transientUIStateRepository;
@property(readonly, nonatomic) IBICCatalogSynchronizer *synchronizer; // @synthesize synchronizer=_synchronizer;
@property(readonly, nonatomic) IBICPasteboardManager *pasteboardManager; // @synthesize pasteboardManager=_pasteboardManager;
@property(readonly) NSArray *ideTopLevelStructureObjects; // @synthesize ideTopLevelStructureObjects=_ideTopLevelStructureObjects;
- (void).cxx_destruct;
- (id)activityReporterForWorkspaceDocument:(id)arg1;
- (void)updateActivityReportsForRegisteredEditorChanges:(CDUnknownBlockType)arg1;
- (id)activityReporters;
- (void)purgeAllActivities;
- (void)activityDidEndForItem:(id)arg1;
- (void)activityDidUpdateForItem:(id)arg1;
- (void)activityDidStartForItem:(id)arg1;
- (id)issueBadgeForCatalogItem:(id)arg1 accountingForChildren:(BOOL)arg2 ofSize:(double)arg3;
- (id)issuesForCatalogItem:(id)arg1 includeChildIssues:(BOOL)arg2;
- (void)populateIssues:(id)arg1 forCatalogItem:(id)arg2 includeChildIssues:(BOOL)arg3;
- (id)ibInspectedCompressionTypeNilPlaceholder;
- (void)setIbInspectedCompressionType:(id)arg1;
- (id)ibInspectedCompressionType;
- (unsigned long long)navigableItem_indexOfRepresentedObjectForIdentifier:(id)arg1 inRelationshipKeyPath:(id)arg2;
- (id)navigableItem_identifierForRepresentedObjectAtIndex:(unsigned long long)arg1 inRelationshipKeyPath:(id)arg2;
- (void)refreshTopLevelStructureItems;
- (void)setIdeTopLevelStructureObjects:(id)arg1;
- (id)importContentsOfFileReferences:(id)arg1 insertionAnchor:(id)arg2;
- (id)importContentOfPaths:(id)arg1 insertionAnchor:(id)arg2;
- (void)applyRemoveItemsChange:(id)arg1;
- (void)applyRemoveItemChange:(id)arg1;
- (void)applyModifyManifestPropertyForItem:(id)arg1 value:(id)arg2 forKeyPath:(id)arg3;
- (void)applyLinkImageRepContent:(id)arg1 toContentOfSibling:(id)arg2;
- (void)applyMoveItems:(id)arg1 toParent:(id)arg2 updateIdentifierToBeUnique:(BOOL)arg3 preserveReferences:(BOOL)arg4;
- (void)applyMoveItem:(id)arg1 toParent:(id)arg2 updateIdentifierToBeUnique:(BOOL)arg3 preserveReferences:(BOOL)arg4;
- (void)applyAddItem:(id)arg1 andUpdateIdentifierToBeUnique:(BOOL)arg2 toParent:(id)arg3;
- (void)applyInsertItem:(id)arg1 atOptionalIndex:(id)arg2 andUpdateIdentifierToBeUnique:(BOOL)arg3 toParent:(id)arg4;
- (void)applyReorderItem:(id)arg1 toIndex:(long long)arg2;
- (void)applyRenameItem:(id)arg1 toFileName:(id)arg2 preserveReferences:(BOOL)arg3;
- (id)targetIdioms;
- (id)idiomNameFromBuildIdentifier:(id)arg1;
@property(readonly, nonatomic) IBFileBuildSettingsSnapshot *buildSettingsSnapshot;
- (id)workspaceDocuments;
- (void)catalogDidRecoverFromFailureByReplaceContentWithContentFromDisk:(id)arg1 result:(id)arg2;
- (void)catalogWillRecoverFromFailureByReplaceContentWithContentFromDisk:(id)arg1;
- (void)catalogSynchronizerDidDetectExternalChangesOnDisk:(id)arg1;
- (void)catalogSynchronizer:(id)arg1 didCompleteSynchronizingWithStatus:(long long)arg2 error:(id)arg3;
- (void)presentErrorOnBestDocumentEditor:(id)arg1;
- (void)imageCatalogItemDidChangeDisplayOrderedChildren:(id)arg1;
- (void)imageCatalogItemDidUpdateIssues:(id)arg1;
- (void)imageCatalogItem:(id)arg1 willChangeKey:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4;
- (void)batchValidateIssues:(id)arg1;
- (void)didExternallyRelocateFileContent;
- (void)willExternallyRelocateFileContent;
- (void)editorDocumentWillClose;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)addImpliedCounterparts;
- (void)applyAddImpliedCounterpartsChangesToItem:(id)arg1;
- (void)saveToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) BOOL supportsSlicing;
- (void)tellEditorsToReplaceSelectionOfItems:(id)arg1 withItem:(id)arg2;
- (void)unregisterImageCatalogDocumentEditor:(id)arg1;
- (void)registerImageCatalogDocumentEditor:(id)arg1;
@property(readonly, nonatomic) IBICAbstractCatalog *catalog;
- (void)applyChanges:(id)arg1;
- (void)applyChange:(id)arg1;
- (void)catalogSynchronizer:(id)arg1 didApplyMutationToModel:(id)arg2;
- (void)finishReplacingContent;
- (void)beginReplacingContent;
- (Class)catalogClass;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

