//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEMediaResourceFoldingStrategy.h"

@class NSSet, NSString;

@interface IBICMediaResourceFoldingStrategy : IDEMediaResourceFoldingStrategy
{
    NSString *_platform;
    NSSet *_idioms;
}

+ (id)bestMatchUsingObjects:(id)arg1 getAttributeValueUsing:(CDUnknownBlockType)arg2 scaleFactor:(double)arg3 deviceIdiom:(long long)arg4 deviceSubtype:(unsigned long long)arg5 displayGamut:(long long)arg6 deploymentTarget:(long long)arg7 layoutDirection:(long long)arg8 sizeClassHorizontal:(long long)arg9 sizeClassVertical:(long long)arg10 memoryClass:(long long)arg11 graphicsFeatureSetClass:(long long)arg12 graphicsFallBackOrder:(id)arg13;
@property(copy, nonatomic) NSSet *idioms; // @synthesize idioms=_idioms;
@property(copy, nonatomic) NSString *platform; // @synthesize platform=_platform;
- (void).cxx_destruct;
- (id)description;
- (id)firstResourceMatchingVariant:(id)arg1 fromVariantSet:(id)arg2;
- (long long)valueForSlotComponentClass:(Class)arg1 inVariant:(id)arg2 withFallbackVariant:(id)arg3;
- (id)initWithPlatform:(id)arg1 andIdioms:(id)arg2;

@end

