//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

@class NSMutableSet, NSSet;

@interface IBMenuTargetResponderForwarder : NSResponder
{
    NSMutableSet *_actionWhitelist;
    NSResponder *_targetResponder;
}

@property(readonly, nonatomic) NSSet *actionWhitelist; // @synthesize actionWhitelist=_actionWhitelist;
@property(retain, nonatomic) NSResponder *targetResponder; // @synthesize targetResponder=_targetResponder;
- (void).cxx_destruct;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)responderChainTargetForSelector:(SEL)arg1;
- (BOOL)wantsToHandleAction:(SEL)arg1;
- (void)addActionsToWhitelist:(id)arg1;
- (id)init;

@end

