//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTabViewItem.h>

@class IBNSViewController;

@interface IBNSTabViewItem : NSTabViewItem
{
    IBNSViewController *_ibViewController;
}

@property(nonatomic) __weak IBNSViewController *ibViewController; // @synthesize ibViewController=_ibViewController;
- (void).cxx_destruct;
- (id)label;

@end

