//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBSourceCodeConnectionContext.h>

@class NSDictionary;

@interface IBOutletSourceCodeConnectionContext : IBSourceCodeConnectionContext
{
    long long _storageType;
    long long _preferredDefaultStorageType;
}

@property(nonatomic) long long preferredDefaultStorageType; // @synthesize preferredDefaultStorageType=_preferredDefaultStorageType;
@property long long storageType; // @synthesize storageType=_storageType;
- (void)saveStorageTypeSelectionToDocument;
- (id)outletTeardownCounterparts;
- (long long)effectivePropertyObjCStorageType;
- (long long)effectiveInstanceVariableObjCStorageType;
- (long long)primitiveEffectiveInternalStorageType;
@property(readonly) NSDictionary *validStorageTypes;
- (Class)userConfigurableOptionsViewControllerClass;
- (BOOL)shouldAllowUserToConfigureStorageType;
- (void)setDocument:(id)arg1;
- (id)validatedSourceCodeConnectionNameForName:(id)arg1 error:(id *)arg2;
- (id)insertionConnectionTypeString;
- (double)positionPriority;

@end

