//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBRefactoringOperation.h>

@class NSString;

@interface IBOutletMoveRefactoringOperation : IBRefactoringOperation
{
    NSString *_outletName;
    NSString *_oldClassName;
    NSString *_newClassName;
}

@property(readonly) NSString *newClassName; // @synthesize newClassName=_newClassName;
@property(readonly) NSString *oldClassName; // @synthesize oldClassName=_oldClassName;
@property(readonly) NSString *outletName; // @synthesize outletName=_outletName;
- (void).cxx_destruct;
- (BOOL)refactorObject:(id)arg1 inDocument:(id)arg2 error:(id *)arg3;
- (id)initWithOutletName:(id)arg1 oldClassName:(id)arg2 andNewClassName:(id)arg3;

@end

