//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class IBStoryboardCanvasBackgroundOverlayView, IBStoryboardCanvasLinkPath, NSEvent;

@protocol IBStoryboardCanvasBackgroundOverlayViewDelegate <NSObject>
- (void)canvasBackgroundOverlayView:(IBStoryboardCanvasBackgroundOverlayView *)arg1 smartMagnifyCanvasLinkPath:(IBStoryboardCanvasLinkPath *)arg2 withEvent:(NSEvent *)arg3;
- (void)canvasBackgroundOverlayView:(IBStoryboardCanvasBackgroundOverlayView *)arg1 canvasLinkPathWasClicked:(IBStoryboardCanvasLinkPath *)arg2 withMouseDownEvent:(NSEvent *)arg3;
- (void)canvasBackgroundOverlayView:(IBStoryboardCanvasBackgroundOverlayView *)arg1 canvasLinkPathWasDoubleClicked:(IBStoryboardCanvasLinkPath *)arg2 withMouseDownEvent:(NSEvent *)arg3;
@end

