//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IBFoundation/IBAbstractSourceCodeSymbolFormatter.h>

@interface IBSwiftSourceCodeSymbolFormatter : IBAbstractSourceCodeSymbolFormatter
{
}

+ (id)nameOfFormattedClassSymbol:(id)arg1;
+ (id)formattedClassSymbolWithName:(id)arg1 namespaceProvider:(id)arg2;

@end

