//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBCocoaTouchStoryboardAbstractShowSegue.h>

@interface IBCocoaTouchStoryboardShowDetailSegue : IBCocoaTouchStoryboardAbstractShowSegue
{
}

+ (id)classIdentifier;
+ (id)defaultAction;
+ (double)displayOrderPriority;
- (id)effectiveConnectionForDisablingConfigurationsInDocument:(id)arg1 segueReachabilityContext:(id)arg2;
- (id)metricChainSucceedingMetric:(id)arg1;

@end

