//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/NSObject-Protocol.h>

@class IBDocumentArchiver, IBDocumentUnarchiver;

@protocol IBDocumentArchiving <NSObject>
- (void)unarchiveWithDocumentUnarchiver:(IBDocumentUnarchiver *)arg1;
- (void)archiveWithDocumentArchiver:(IBDocumentArchiver *)arg1;

@optional
+ (id)instantiateWithDocumentUnarchiver:(IBDocumentUnarchiver *)arg1;
- (void)awakeAfterUsingDocumentUnarchiver:(IBDocumentUnarchiver *)arg1;
- (Class)classForDocumentArchiver:(IBDocumentArchiver *)arg1;
@end

