//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IBAutolayoutFoundation/IBLayoutConstraint.h>

@interface IBLayoutConstraint (IBUILayoutConstraintIntegration)
- (void)ibPrepareToBackwardsDeployToOSVersion:(id)arg1 inDocument:(id)arg2;
- (void)ibPopulateAdditionalTargetOSVersions:(id)arg1 forCompilingDocument:(id)arg2;
- (id)targetRuntime;
- (Class)classToTakeInitialMarshalledKeysFrom:(id)arg1;
@end

