//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DVTSourceControlHostedAccount.GitHubPlan : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: space
    // Error parsing type: , name: privateRepos
    // Error parsing type: , name: collaborators
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long collaborators; // @synthesize collaborators;
@property(nonatomic, readonly) long long privateRepos; // @synthesize privateRepos;
@property(nonatomic, readonly) long long space; // @synthesize space;
@property(nonatomic, readonly) NSString *name; // @synthesize name;

@end

