//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTAnalytics/DVTAnalyticsPointAbstractClass.h>

@class DVTAnalyticsPointDistributionInfo, DVTFilePath, NSString, NSURL, _TtC12DVTAnalytics23ProcessorUsagePointInfo, _TtC12DVTAnalytics35ProcessorUsagePointDistributionInfo;
@protocol DVTAnalyticsPointIdentifierProtocol, DVTAnalyticsPointUserDataProtocol;

@interface _TtC12DVTAnalytics19ProcessorUsagePoint : DVTAnalyticsPointAbstractClass
{
    // Error parsing type: , name: pointInfo
    // Error parsing type: , name: processorUsagePointDistributionInfo
    // Error parsing type: , name: path
    // Error parsing type: , name: filename.storage
}

+ (id)logsRelativePath;
+ (id)distributionInfosAllRelativePath;
+ (id)pathExtension;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *inspectableIconImageName;
@property(nonatomic, readonly) BOOL isSystemTerminationEvent;
@property(nonatomic, readonly) NSString *inspectableAnalyticsLogReportTypeUserDescription;
@property(nonatomic, readonly) NSString *inspectableAnalyticsLogDetailsSectionTitle;
@property(nonatomic, readonly) NSString *inspectableTypeUserDescription;
@property(nonatomic, readonly) DVTFilePath *cachePath;
@property(nonatomic, readonly) long long sourceFileLine;
@property(nonatomic, readonly) NSString *sourceFileName;
@property(nonatomic, readonly) BOOL isTopPoint;
@property(nonatomic, readonly) DVTAnalyticsPointDistributionInfo *distributionInfo;
@property(nonatomic, readonly) long long uniqueDeviceCount;
@property(nonatomic, readonly) id <DVTAnalyticsPointUserDataProtocol> userData;
@property(nonatomic, readonly) id <DVTAnalyticsPointIdentifierProtocol> analyticsPointIdentifier;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, copy) NSString *filename;
- (id)initWithPath:(id)arg1 error:(id *)arg2;
- (id)initWithPointInfo:(id)arg1 processorUsagePointDistributionInfo:(id)arg2 path:(id)arg3 analyticsLogProvider:(id)arg4;
@property(nonatomic, copy) NSURL *path; // @synthesize path;
@property(nonatomic, retain) _TtC12DVTAnalytics35ProcessorUsagePointDistributionInfo *processorUsagePointDistributionInfo; // @synthesize processorUsagePointDistributionInfo;
@property(nonatomic, retain) _TtC12DVTAnalytics23ProcessorUsagePointInfo *pointInfo; // @synthesize pointInfo;

@end

