//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTLogAspect, NSString;

@interface _TtC12DVTAnalytics34AnalyticsAppStoreSourceRateLimiter : NSObject
{
    // Error parsing type: , name: lastRecordedRefreshKey
    // Error parsing type: , name: logAspect
    // Error parsing type: , name: rateLimit
}

+ (void)setOverrideRateLimit:(BOOL)arg1;
+ (BOOL)overrideRateLimit;
+ (id)lastRecordedRefreshKey;
+ (id)rateLimitOverrideKey;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) BOOL isAllowedToRefresh;
- (id)lastRefresh;
- (void)refreshedOn:(id)arg1;
- (id)initWithAppIdentifier:(id)arg1 sourceType:(long long)arg2;
- (id)initWithKey:(id)arg1 rateLimit:(double)arg2;
@property(nonatomic, readonly) double rateLimit; // @synthesize rateLimit;
@property(nonatomic, readonly) DVTLogAspect *logAspect; // @synthesize logAspect;
@property(nonatomic, readonly) NSString *lastRecordedRefreshKey; // @synthesize lastRecordedRefreshKey;

@end

