//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBSubviewEmbeddingPolicy.h>

@interface IBMatrixEmbeddingPolicy : IBSubviewEmbeddingPolicy
{
}

- (BOOL)canEmbedObjects:(id)arg1 fromDocument:(id)arg2;
- (id)embedObjects:(id)arg1 fromDocument:(id)arg2 context:(id)arg3;
- (void)transitionControlsCell:(id)arg1 toMatrix:(id)arg2 inDocument:(id)arg3 row:(long long)arg4 col:(long long)arg5;

@end

