//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaIntegration/IBNSViewEditor.h>

#import <IDEInterfaceBuilderCocoaIntegration/IBNSStackViewGravityAreaDropTargetResolverDelegate-Protocol.h>

@interface IBNSStackViewGravityAreaEditor : IBNSViewEditor <IBNSStackViewGravityAreaDropTargetResolverDelegate>
{
}

+ (Class)ibDropTargetResolverClass;
- (id)acceptDragInfo:(id)arg1 context:(id)arg2;
- (void)dropTargetResolver:(id)arg1 dropGravity:(long long)arg2 insertionIndexDidChange:(long long)arg3;
- (void)dropTargetResolver:(id)arg1 dropGravity:(long long)arg2 insertionIndexWillChange:(long long)arg3;
- (void)reattachDraggedObjects:(id)arg1 dragContext:(id)arg2;
- (void)detachDraggedObjects:(id)arg1 dragContext:(id)arg2;
- (void)dragSelectedViewsWithMouseDown:(id)arg1 andMouseDragged:(id)arg2;
- (id)guideContextForDraggingInfo:(id)arg1;
- (id)installedChildViewsInRect:(struct CGRect)arg1;
- (id)editedStackView;

@end

