//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaIntegration/IBDateTokenizer.h>

@class NSArray;

@interface IBUnicodeTR354Tokenizer : IBDateTokenizer
{
    NSArray *_quarterOptions;
    NSArray *_weekdayOptions;
    NSArray *_periodOptions;
    NSArray *_minuteOptions;
    NSArray *_secondOptions;
    NSArray *_monthOptions;
    NSArray *_yearOptions;
    NSArray *_weekOptions;
    NSArray *_hourOptions;
    NSArray *_zoneOptions;
    NSArray *_dayOptions;
    NSArray *_eraOptions;
}

+ (long long)fieldTypeForUnichar:(unsigned short)arg1;
+ (id)_possibleFieldTypes;
@property(retain) NSArray *eraOptions; // @synthesize eraOptions=_eraOptions;
@property(retain) NSArray *dayOptions; // @synthesize dayOptions=_dayOptions;
@property(retain) NSArray *zoneOptions; // @synthesize zoneOptions=_zoneOptions;
@property(retain) NSArray *hourOptions; // @synthesize hourOptions=_hourOptions;
@property(retain) NSArray *weekOptions; // @synthesize weekOptions=_weekOptions;
@property(retain) NSArray *yearOptions; // @synthesize yearOptions=_yearOptions;
@property(retain) NSArray *monthOptions; // @synthesize monthOptions=_monthOptions;
@property(retain) NSArray *secondOptions; // @synthesize secondOptions=_secondOptions;
@property(retain) NSArray *minuteOptions; // @synthesize minuteOptions=_minuteOptions;
@property(retain) NSArray *periodOptions; // @synthesize periodOptions=_periodOptions;
@property(retain) NSArray *weekdayOptions; // @synthesize weekdayOptions=_weekdayOptions;
@property(retain) NSArray *quarterOptions; // @synthesize quarterOptions=_quarterOptions;
- (void).cxx_destruct;
- (void)_regenerateTokenOptions;
- (void)setDelegate:(id)arg1;
- (id)_zoneTokenWithType:(id)arg1 count:(id)arg2;
- (id)_secondTokenWithType:(id)arg1 count:(id)arg2;
- (id)_minuteTokenWithType:(id)arg1 count:(id)arg2;
- (id)_hourTokenWithType:(id)arg1 count:(id)arg2;
- (id)_periodTokenWithType:(id)arg1 count:(id)arg2;
- (id)_weekdayTokenWithType:(id)arg1 count:(id)arg2;
- (id)_dayTokenWithType:(id)arg1 count:(id)arg2;
- (id)_weekTokenWithType:(id)arg1 count:(id)arg2;
- (id)_monthTokenWithType:(id)arg1 count:(id)arg2;
- (id)_quarterTokenWithType:(id)arg1 count:(id)arg2;
- (id)_yearTokenWithType:(id)arg1 count:(id)arg2;
- (id)_eraTokenWithType:(id)arg1 count:(id)arg2;
- (id)_possibleFieldSelectors;
- (id)_matchPattern:(unsigned short)arg1 count:(unsigned long long)arg2;
- (id)tokenizeString:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

