//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSLevelIndicatorCell.h>

@interface NSLevelIndicatorCell (IBNSLevelIndicatorCellIntegration)
+ (id)keyPathsForValuesAffectingIbStyleIsRating;
+ (id)keyPathsForValuesAffectingIbStyleIsCapacity;
+ (id)keyPathsForValuesAffectingIbInspectedLevelIndicatorStyle;
- (long long)ibPreferredResizeDirection;
- (Class)ibPreferredControlClass;
- (unsigned long long)ibPreferredMatrixMode;
- (id)ibAcceptContentsOfPasteboard:(id)arg1 inDocument:(id)arg2 insertionContext:(id)arg3;
- (BOOL)ibCanAcceptContentsOfPasteboard:(id)arg1 inDocument:(id)arg2 targetChildRelation:(id *)arg3;
- (id)ibWidgetType;
- (id)ibOrderedSnapshotAttributesKeyPaths;
- (void)setIbInspectedImage:(id)arg1;
- (id)ibInspectedImage;
- (BOOL)ibShouldArchiveImage;
- (BOOL)ibStyleIsRating;
- (BOOL)ibStyleIsCapacity;
- (void)setIbInspectedLevelIndicatorStyle:(unsigned long long)arg1;
- (unsigned long long)ibInspectedLevelIndicatorStyle;
@property unsigned long long ibArchivedTickMarkPosition;
- (id)ibLocalAttributeKeyPaths;
@end

