//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTDiagnosticsClient.h"

@class NSMutableDictionary, NSString;

@interface DVTDiagnosticsXcodeSupport : NSObject <DVTDiagnosticsClient>
{
    NSMutableDictionary *_info;
}

@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (id)unknownPlatform;
- (id)_captureSDKInfoUsingPlatform:(id)arg1 xcodePath:(id)arg2;
- (void)_captureAllSDKInfo:(id)arg1;
- (id)_selectedXcodePath;
- (void)_captureXcodeInfo:(id)arg1;
- (void)collect:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

