//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESourceCodeComparisonEditor/_TtC29IDESourceCodeComparisonEditor16BlameSidebarView.h>

@interface _TtC29IDESourceCodeComparisonEditor19BlameBackgroundView : _TtC29IDESourceCodeComparisonEditor16BlameSidebarView
{
    // Error parsing type: , name: borderLayer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

