//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESourceCodeComparisonEditor/DVTDiffSessionObserver-Protocol.h>

@class DVTDiffSession, NSArray, NSDictionary;

@interface IDESourceCodeComparisonEditor.TwoUpVisualization : NSObject <DVTDiffSessionObserver>
{
    // Error parsing type: , name: primarySourceEditorView
    // Error parsing type: , name: secondarySourceEditorView
    // Error parsing type: , name: layoutCallback
    // Error parsing type: , name: invalidateAllPrimaryLayers
    // Error parsing type: , name: invalidateAllSecondaryLayers
    // Error parsing type: , name: diffSession
    // Error parsing type: , name: primaryLayersByIndex
    // Error parsing type: , name: secondaryLayersByIndex
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didLayoutInContentView:(id)arg1;
@property(nonatomic, copy) NSDictionary *secondaryLayersByIndex; // @synthesize secondaryLayersByIndex;
@property(nonatomic, copy) NSDictionary *primaryLayersByIndex; // @synthesize primaryLayersByIndex;
- (void)willLayoutInContentView:(id)arg1;
@property(nonatomic, readonly) NSArray *hitTestViews;
- (void)removeFromSecondarySourceEditorView:(id)arg1;
- (void)removeFromPrimarySourceEditorView:(id)arg1;
- (void)addToSecondarySourceEditorView:(id)arg1;
- (void)addToPrimarySourceEditorView:(id)arg1;
- (void)diffSessionDidChange;
@property(nonatomic, retain) DVTDiffSession *diffSession; // @synthesize diffSession;
@property(nonatomic, copy) CDUnknownBlockType layoutCallback; // @synthesize layoutCallback;

@end

