//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface GPUGradientPainter : NSObject
{
}

+ (void)gradientSeperatorLineWithRect:(struct CGRect)arg1;
+ (void)gradientFillFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2;

@end

