//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <GPUTraceDebuggerUI/DVTFilterTokenFieldControllerDelegate-Protocol.h>
#import <GPUTraceDebuggerUI/DVTInvalidation-Protocol.h>
#import <GPUTraceDebuggerUI/IDEDebugNavigableContentDelegate-Protocol.h>

@class DVTStackBacktrace, GPUDebuggingAdditionUIController, GPUFilterCompletionsEngine, GPUFilterTokenHelper, GPUNavigableItemFilteringCoordinator, GPUNavigatorFilterControlBar, GPUSharedTabUIState, GPUTraceCountersTrayCell, GPUTraceDisplayableItem, GPUTracePopover, GPUTraceProcessItem, IDEDebugNavigator, IDEDebugSession, IDENavigatorOutlineView, NSArray, NSMenuItem, NSString, NSTrackingArea;
@protocol DVTCancellable, NSObject;

__attribute__((visibility("hidden")))
@interface GPUTraceContentDelegate : NSObject <DVTFilterTokenFieldControllerDelegate, IDEDebugNavigableContentDelegate, DVTInvalidation>
{
    GPUTraceProcessItem *_processItem;
    NSString *_associatedProcessUUID;
    unsigned long long _navigatorProgramSortMode;
    GPUDebuggingAdditionUIController *_debuggingAdditionUIController;
    GPUSharedTabUIState *_sharedUIStateObj;
    IDENavigatorOutlineView *_outlineView;
    NSMenuItem *_traceItemMenuItem;
    BOOL _ignoreStateForDebugNavigator;
    BOOL _haveRequestedUIController;
    BOOL _shaderEditContinueActive;
    id <DVTCancellable> _uiControllerObserver;
    id <DVTCancellable> _sessionStateObserver;
    id <NSObject> _scrubberNotificationObserver;
    id <NSObject> _shaderEditContinueBeginObserver;
    id <NSObject> _shaderEditContinueEndObserver;
    GPUNavigableItemFilteringCoordinator *_filteringCoordinator;
    GPUNavigatorFilterControlBar *_filterControlBar;
    NSArray *_filterMatchStrings;
    GPUFilterTokenHelper *_tokenHelper;
    GPUFilterCompletionsEngine *_tokenCompletionEngine;
    GPUTraceCountersTrayCell *_countersCell;
    GPUTracePopover *_thumbnailPopover;
    NSTrackingArea *_trackArea;
    BOOL _mouseInside;
    BOOL _thumbnailDisplay;
    BOOL _thumbnailTooltipDisplay;
    GPUTraceDisplayableItem *_previousDisplay;
    BOOL _windowWasAcceptingMouseEvents;
    BOOL _showOnlyIssues;
    BOOL _showOnlyInterestingContent;
    IDEDebugNavigator *_debugNavigator;
    IDEDebugSession *_debugSession;
    long long _stackFrameFilter;
    unsigned long long _traceOutlineMode;
}

+ (void)initialize;
@property(nonatomic) BOOL showOnlyInterestingContent; // @synthesize showOnlyInterestingContent=_showOnlyInterestingContent;
@property(nonatomic) unsigned long long traceOutlineMode; // @synthesize traceOutlineMode=_traceOutlineMode;
@property(nonatomic) BOOL showOnlyIssues; // @synthesize showOnlyIssues=_showOnlyIssues;
@property(nonatomic) long long stackFrameFilter; // @synthesize stackFrameFilter=_stackFrameFilter;
@property(readonly) IDEDebugSession *debugSession; // @synthesize debugSession=_debugSession;
@property(readonly) IDEDebugNavigator *debugNavigator; // @synthesize debugNavigator=_debugNavigator;
- (void).cxx_destruct;
- (void)_addSelfAndDescendentArchRepsFor:(id)arg1 archReps:(id)arg2;
- (void)_revealInGPUGauge:(id)arg1;
- (void)_revealInIssueNavigator:(id)arg1;
- (void)_outlineItem:(id)arg1 toIssues:(id)arg2;
- (void)_showAPIDoc:(id)arg1;
- (id)_outlineItemForClickOrSelection;
- (id)trayCellsForProcessHeader;
- (id)_trayCountersCell;
- (void)filterTokenFieldController:(id)arg1 tokensDidUpdate:(id)arg2 editingString:(id)arg3 globalOperator:(int)arg4;
- (id)_highlightEnabledFilterIDs;
- (id)filterTokenFieldController:(id)arg1 completionTokensForString:(id)arg2;
- (void)updateForNewFilterString:(id)arg1;
- (void)primitiveInvalidate;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (id)_navigableItemsForProcessItem:(id)arg1 withTokens:(id)arg2 ofClass:(Class)arg3;
- (void)_updateForNewStackFrameFilter;
- (void)_updateForNewProgramSortMode:(unsigned long long)arg1;
- (void)_recordPersistenceStateChangesIfNecessary;
- (void)_updateForNewTraceOutlineMode:(id)arg1;
- (void)configureMenuForProcessHeaderActionPopUpCell:(id)arg1;
- (void)_threadContextuallyClicked;
- (void)contextualMenuNeedsUpdate:(id)arg1;
- (void)_showAllIssues:(id)arg1;
- (void)_showHighAndMediumIssues:(id)arg1;
- (void)_showHighIssues:(id)arg1;
- (void)_setProgramSortByCost:(id)arg1;
- (void)_setProgramSortByProgram:(id)arg1;
- (void)_setProgramMetricsAsPercentage:(id)arg1;
- (void)_setProgramMetricsAsTime:(id)arg1;
- (void)_setShowShaderProfilingInFrameNavigator:(id)arg1;
- (void)_setHideShaderProfilingInFrameNavigator:(id)arg1;
- (void)_setTextModeCompact:(id)arg1;
- (void)_setTextModeVerbose:(id)arg1;
- (void)_refreshNavigator;
- (BOOL)shouldExpandItemAsResultOfOptionClick:(id)arg1 clickedItem:(id)arg2;
- (BOOL)validateUserInterfaceAction:(SEL)arg1 forRepresentedObject:(id)arg2;
- (BOOL)validateUserInterfaceAction:(SEL)arg1;
- (id)representedObjectsToReveal;
- (void)revealRepresentedObjects:(id)arg1;
- (id)pasteboardStringForRepresentedObject:(id)arg1;
- (void)_appendDisplayStringForCopiedOrDraggedGroupItem:(id)arg1 toString:(id)arg2 level:(unsigned int)arg3;
- (BOOL)shouldHandleUserDirectMoveUpOrDown:(BOOL)arg1 forRepresentedObject:(id)arg2 newRow:(long long *)arg3;
- (void)didCollapseForItem:(id)arg1;
- (void)didExpandForItem:(id)arg1;
- (void)_handleExpandStateForGroupItem:(id)arg1 expanded:(BOOL)arg2;
- (void)willExpandForItem:(id)arg1;
- (void)_willExpandForItemDefault:(id)arg1;
- (void)_willExpandForItemRevertFilterString:(id)arg1;
- (void)_willExpandForItemApplyFilterString:(id)arg1;
- (void)handleExpandForItem:(id)arg1;
- (id)expandableItemsForProcessItem:(id)arg1 tokens:(id)arg2;
- (void)_recursiveExpanableItemsWithItem:(id)arg1 tokens:(id)arg2 output:(id)arg3;
- (id)tokenForExpandedRepresentedObject:(id)arg1;
- (id)persistentNameForRepresentedObject:(id)arg1;
- (id)launchSessionForSelectedRepresentedObject:(id)arg1;
- (void)openSelectedRepresentedObject:(id)arg1 withEventType:(unsigned long long)arg2;
- (BOOL)_shouldLockOutUserNavigation;
- (id)_documentLocationForRepresentedObject:(id)arg1;
- (BOOL)shouldSelectItemForRepresentedObject:(id)arg1 withPrevious:(id)arg2 next:(id)arg3;
- (double)heightOfRowForRepresentedObject:(id)arg1;
- (id)filterView;
- (void)registerTableCellViewsWithOutlineView:(id)arg1;
- (id)tableCellViewForRepresentedObject:(id)arg1 withOutlineView:(id)arg2;
- (id)relatedDisplayablesTableCellViewWithOutlineView:(id)arg1;
- (id)commandEncoderHeaderTableCellViewWithOutlineView:(id)arg1;
- (id)commandBufferHeaderTableCellViewWithOutlineView:(id)arg1;
- (id)contextHeaderTableCellViewWithOutlineView:(id)arg1;
- (id)standardOneLineTableCellViewForIdentifier:(id)arg1 withOutlineView:(id)arg2;
- (id)displayableProgramOrShaderTableCellViewWithOutlineView:(id)arg1;
- (id)displayableItemTableCellViewWithOutlineView:(id)arg1;
- (void)addSubtitleStatusViewToTableCellView:(id)arg1;
- (void)addSeverityStatusViewToTableCellView:(id)arg1;
- (id)markerGroupTableCellViewWithOutlineView:(id)arg1;
- (void)willDisplayCell:(id)arg1 forRepresentedObject:(id)arg2 item:(id)arg3;
- (void)_selectOutlineItem:(id)arg1 openLocation:(BOOL)arg2;
- (BOOL)_navigatorFirstShownWithNoSelectedItems;
- (void)_onShaderEditContinueNotificationReceived:(id)arg1;
- (void)_onScrubberNotificationReceived:(id)arg1;
- (void)_handleDebuggingAdditionUIControllerCreated:(id)arg1;
- (void)debugNavigatorViewWillUninstall;
- (void)debugNavigatorViewDidInstall;
@property(readonly) NSString *associatedProcessUUID;
- (id)processNavigableItem;
- (id)workspaceTabController;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)_resetTooltip;
- (void)_resetHover;
- (void)_thumbnailTooltip;
- (void)_thumbnailHover;
- (double)_thumbnailHoverDelay;
- (double)_thumbnailTooltipDelay;
- (void)boundsDidChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_thumbnailUpdate;
- (void)_updateThumbnailWithPointInWindow:(struct CGPoint)arg1 enableOffset:(BOOL)arg2;
- (id)_findThumbnailDisplayableForItem:(id)arg1;
- (struct CGRect)_thumbnailRectWithMouse:(struct CGPoint)arg1;
- (void)_updateTrackArea;
- (id)initWithTopNavigableModel:(id)arg1 debugNavigator:(id)arg2;
- (id)tableViewCellPropertyBindingsForCell:(id)arg1;
- (void)showAPIDocForItem:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

