//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class GPUTraceFramePlayheadSlider;

@protocol GPUTraceFramePlayheadSliderDelegate
- (void)scrubber:(GPUTraceFramePlayheadSlider *)arg1 onMouseExitAtPoint:(struct CGPoint)arg2;
- (void)scrubber:(GPUTraceFramePlayheadSlider *)arg1 onMouseMoveAtPoint:(struct CGPoint)arg2;
- (void)scrubber:(GPUTraceFramePlayheadSlider *)arg1 onMouseEnterAtPoint:(struct CGPoint)arg2;
@end

