//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMenuItem, NSString;

@interface GPUTraceCounterGraphGroupItem : NSObject
{
    BOOL _maskInCompute;
    int _resourceLink;
    NSArray *_subPlaneIndexes;
    NSString *_name;
    NSMenuItem *_contextMenuItem;
}

@property(nonatomic) int resourceLink; // @synthesize resourceLink=_resourceLink;
@property(nonatomic) BOOL maskInCompute; // @synthesize maskInCompute=_maskInCompute;
@property(retain, nonatomic) NSMenuItem *contextMenuItem; // @synthesize contextMenuItem=_contextMenuItem;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSArray *subPlaneIndexes; // @synthesize subPlaneIndexes=_subPlaneIndexes;
- (void).cxx_destruct;

@end

