//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <DebugHierarchyKit/NSObject-Protocol.h>

@class NSString;

@protocol DBGValueJSONSerialization <NSObject>
+ (id)valueWithEncodedValue:(id)arg1 format:(NSString *)arg2 error:(id *)arg3;
- (id)JSONCompatibleRepresentation;
@end

