//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DebuggerUI/DBGBorderNode.h>

@class DBGNode, SCNNode;

@interface DBGRectBorderNode : DBGBorderNode
{
    SCNNode *_topLeft;
    SCNNode *_bottomLeft;
    SCNNode *_bottomRight;
    SCNNode *_topRight;
    DBGNode *_topEdgeNode;
    DBGNode *_leftEdgeNode;
    DBGNode *_bottomEdgeNode;
    DBGNode *_rightEdgeNode;
    struct CGRect _borderRect;
    struct CGRect _clippingRect;
}

+ (id)borderNodeWithRect:(struct CGRect)arg1 addToParentNode:(id)arg2 sceneView:(id)arg3;
@property(retain, nonatomic) DBGNode *rightEdgeNode; // @synthesize rightEdgeNode=_rightEdgeNode;
@property(retain, nonatomic) DBGNode *bottomEdgeNode; // @synthesize bottomEdgeNode=_bottomEdgeNode;
@property(retain, nonatomic) DBGNode *leftEdgeNode; // @synthesize leftEdgeNode=_leftEdgeNode;
@property(retain, nonatomic) DBGNode *topEdgeNode; // @synthesize topEdgeNode=_topEdgeNode;
@property(retain, nonatomic) SCNNode *topRight; // @synthesize topRight=_topRight;
@property(retain, nonatomic) SCNNode *bottomRight; // @synthesize bottomRight=_bottomRight;
@property(retain, nonatomic) SCNNode *bottomLeft; // @synthesize bottomLeft=_bottomLeft;
@property(retain, nonatomic) SCNNode *topLeft; // @synthesize topLeft=_topLeft;
@property(nonatomic) struct CGRect clippingRect; // @synthesize clippingRect=_clippingRect;
@property(nonatomic) struct CGRect borderRect; // @synthesize borderRect=_borderRect;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGRect effectiveBorderRect;
- (void)updateEffectiveBorderRect;
- (id)lineNodes;
- (void)setupLines;
- (id)initWithBorderRect:(struct CGRect)arg1 addToParentNode:(id)arg2 sceneView:(id)arg3;

@end

