//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTextFieldDelegate.h"

@class DBGBreakpointEditorCompletingTextView, DVTTextDocumentLocation, IDEAppleScriptBreakpointAction, NSImageView, NSString, NSTextField;

@interface IDEAppleScriptBreakpointActionEditor : NSViewController <NSTextFieldDelegate>
{
    IDEAppleScriptBreakpointAction *_action;
    DVTTextDocumentLocation *_breakpointLocation;
    DBGBreakpointEditorCompletingTextView *_script;
    NSImageView *_compileStatusImage;
    NSTextField *_compileStatus;
}

- (void).cxx_destruct;
- (void)completingTextView:(id)arg1 willPassContextToStrategies:(id)arg2 atWordStartLocation:(unsigned long long)arg3;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (void)testScript:(id)arg1;
- (id)_compileScriptAndSetStatusMessage;
- (void)compileScript:(id)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithAction:(id)arg1 breakpointLocation:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

