//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSControl.h>

@class HFController, HFLayoutRepresenter, HFVerticalScrollerRepresenter, NSArray, NSData;

@interface HFTextView : NSControl
{
    HFController *dataController;
    HFLayoutRepresenter *layoutRepresenter;
    HFVerticalScrollerRepresenter *scrollRepresenter;
    NSArray *backgroundColors;
    BOOL bordered;
    id delegate;
    NSData *cachedData;
}

+ (void)initialize;
- (void)dealloc;
- (void)setData:(id)arg1;
- (id)data;
- (BOOL)bordered;
- (void)setBordered:(BOOL)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)setBackgroundColors:(id)arg1;
- (id)backgroundColors;
- (id)byteArray;
- (id)controller;
- (id)layoutRepresenter;
- (void)viewDidMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (struct CGRect)_desiredFrameForLayoutView;
- (void)_HFControllerDidChangeProperties:(id)arg1;
- (void)_sharedInitHFTextViewWithMutableData:(id)arg1;

@end

