//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol DBGSBFileSpec <NSObject>
- (const char *)GetDirectory;
- (const char *)GetFilename;
- (unsigned int)GetPath:(char *)arg1 dst_len:(unsigned long long)arg2;
- (_Bool)Exists;
- (id)initWithConnection:(id)arg1 path:(const char *)arg2 resolve:(_Bool)arg3;
- (id)initWithConnection:(id)arg1 path:(const char *)arg2;
@end

