//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol DBGSBData <NSObject>
- (unsigned long long)ReadRawData:(id <DBGSBError>)arg1 offset:(unsigned long long)arg2 buf:(void *)arg3 size:(unsigned long long)arg4;
- (unsigned long long)GetByteSize;
@end

