//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DBGSBThreadCollection.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface LLDBThreadCollection : NSObject <DBGSBThreadCollection>
{
    struct SBThreadCollection {
        struct shared_ptr<lldb_private::ThreadCollection> m_opaque_sp;
    } _threadCollection;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)GetSize;
- (id)initWithSBThreadCollection:(const struct SBThreadCollection *)arg1;
- (id)GetThreadAtIndex:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

