//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DBGSBValueList.h"

@class NSString;

@interface LLDBValueList : NSObject <DBGSBValueList>
{
    struct SBValueList {
        struct unique_ptr<ValueListImpl, std::__1::default_delete<ValueListImpl>> m_opaque_ap;
    } _valueList;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)GetSize;
- (id)initWithSBValueList:(const struct SBValueList *)arg1;
- (id)GetValueAtIndex:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

