//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DBGSBLineEntry.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface LLDBLineEntry : NSObject <DBGSBLineEntry>
{
    struct SBLineEntry {
        struct unique_ptr<lldb_private::LineEntry, std::__1::default_delete<lldb_private::LineEntry>> m_opaque_ap;
    } _lineEntry;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)GetLine;
- (_Bool)IsValid;
- (id)initWithSBLineEntry:(struct SBLineEntry *)arg1;
- (id)GetStartAddress;
- (id)GetFileSpec;
- (id)initWithConnection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

