//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DBGSBTypeSummaryOptions.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface LLDBTypeSummaryOptions : NSObject <DBGSBTypeSummaryOptions>
{
    struct SBTypeSummaryOptions {
        struct unique_ptr<lldb_private::TypeSummaryOptions, std::__1::default_delete<lldb_private::TypeSummaryOptions>> m_opaque_ap;
    } _typeSummaryOptions;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)SetCapping:(int)arg1;
- (id)initWithConnection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

