//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEInspectorViewController.h>

@class NSString;

@interface _TtC18IDESourceControlUI28FilesInspectorViewController : IDEInspectorViewController
{
    // Error parsing type: , name: status
    // Error parsing type: , name: loadItemsOperation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillUninstall;
- (void)didSetInspectedObjects:(id)arg1;
@property(nonatomic, copy) NSString *status; // @synthesize status;

@end

