//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol GPUBufferViewerLayout <NSObject>
@property(nonatomic) unsigned long long offset;
@property(readonly, nonatomic) BOOL supportsOffset;
@property(readonly, nonatomic) NSString *source;
@property(readonly, nonatomic) NSString *name;
@end

