//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface LOCProperty : NSObject
{
    NSString *filePath;
    NSMutableDictionary *debugInfo;
    NSMutableDictionary *warningInfo;
    BOOL legacyNotValidXLIFF;
}

+ (BOOL)isEnvironmentVariableTrue:(id)arg1;
+ (id)getEnvironmentVariable:(id)arg1;
+ (id)makeTempFilePathWithExtension:(id)arg1;
+ (int)diffFileAtPath:(id)arg1 withPath:(id)arg2 diffOptions:(id)arg3 diffResults:(id *)arg4;
+ (int)diffString:(id)arg1 withString:(id)arg2 diffOptions:(id)arg3 diffResults:(id *)arg4;
+ (BOOL)fileIsIn_OldLoc:(id)arg1;
+ (BOOL)fileIsIn_NewLoc:(id)arg1;
+ (BOOL)fileIsIn_OldBase:(id)arg1;
+ (BOOL)fileIsIn_NewBase:(id)arg1;
+ (BOOL)fileIsInBaseLproj:(id)arg1;
@property BOOL legacyNotValidXLIFF; // @synthesize legacyNotValidXLIFF;
@property(retain) NSMutableDictionary *warningInfo; // @synthesize warningInfo;
@property(retain) NSMutableDictionary *debugInfo; // @synthesize debugInfo;
@property(retain) NSString *filePath; // @synthesize filePath;
- (void).cxx_destruct;
- (BOOL)isEnvironmentVariableTrue:(id)arg1;
- (id)getEnvironmentVariable:(id)arg1;
- (id)deducedGlotEnvPath;
- (int)diffWithLOCProperty:(id)arg1 diffOptions:(id)arg2 diffResults:(id *)arg3;
- (BOOL)fileIsIn_OldLoc;
- (BOOL)fileIsIn_NewLoc;
- (BOOL)fileIsIn_OldBase;
- (BOOL)fileIsIn_NewBase;
- (BOOL)fileIsInBaseLproj;
- (id)notImplementedError;
- (BOOL)writeTo:(id)arg1 withTranslation:(id)arg2 options:(unsigned long long)arg3 error:(id *)arg4;
- (id)createInternalGlossaryRelativeTo:(id)arg1 withError:(id *)arg2;
- (id)createInternalGlossaryWithError:(id *)arg1;
- (id)url;
- (id)debugString;
- (id)warningString;
- (id)initWithContentsOfFile:(id)arg1 error:(id *)arg2;

@end

