//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTSourceControl/DVTSourceControlDisplayable-Protocol.h>
#import <DVTSourceControl/DVTSourceControlSerializable-Protocol.h>
#import <DVTSourceControl/NSCopying-Protocol.h>
#import <DVTSourceControl/NSSecureCoding-Protocol.h>

@class DVTSourceControlAuthor, DVTSourceControlRevision, NSArray, NSDate, NSString;

@interface DVTSourceControlStash : NSObject <DVTSourceControlDisplayable, DVTSourceControlSerializable, NSSecureCoding, NSCopying>
{
    BOOL _hasLoadedCompleteStash;
    unsigned long long _index;
    NSString *_title;
    NSString *_branch;
    DVTSourceControlRevision *_revision;
    NSArray *_fileStatuses;
    DVTSourceControlAuthor *_author;
    NSDate *_date;
    NSString *_message;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) DVTSourceControlAuthor *author; // @synthesize author=_author;
@property(retain, nonatomic) NSArray *fileStatuses; // @synthesize fileStatuses=_fileStatuses;
@property(retain, nonatomic) DVTSourceControlRevision *revision; // @synthesize revision=_revision;
@property(retain, nonatomic) NSString *branch; // @synthesize branch=_branch;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) NSString *displayName;
- (id)loadCompleteStash:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)dictionaryRepresentationWithOptions:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRevision:(id)arg1 index:(unsigned long long)arg2 title:(id)arg3 branch:(id)arg4 author:(id)arg5 date:(id)arg6 fileStatuses:(id)arg7;
- (id)initWithRevision:(id)arg1 index:(unsigned long long)arg2 title:(id)arg3 branch:(id)arg4;
- (id)init:(unsigned long long)arg1 title:(id)arg2 branch:(id)arg3;
- (id)initWithRevision:(id)arg1;
- (id)init:(unsigned long long)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

