//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (VVSyntax)
- (BOOL)vv_isCommentLine;
- (BOOL)vv_isSwiftExtension;
- (BOOL)vv_isSwiftProtocol;
- (BOOL)vv_isSwiftProperty;
- (BOOL)vv_isSwiftEnum;
- (BOOL)vv_isSwiftFunction;
- (BOOL)vv_isCompilerKeyword;
- (BOOL)vv_isUnion;
- (BOOL)vv_isEnum;
- (BOOL)vv_isStruct;
- (BOOL)vv_isMacro;
- (BOOL)vv_isProperty;
- (BOOL)vv_isCFunction;
- (BOOL)vv_isObjCMethod;
- (BOOL)isImport;
- (id)vv_stringByTrimEndSpaces;
- (id)vv_stringByConvertingToUniform;
@end

