//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCSourceTextBufferCategoryClass : NSObject
{
}

+ (BOOL)isWholeFileSelected:(id)arg1;
+ (id)buffer:(id)arg1 firstPlaceholderRangeStartingAtLine:(long long)arg2;
+ (id)buffer:(id)arg1 stringForLineRange:(long long)arg2 endLine:(long long)arg3;
+ (id)buffer:(id)arg1 stringForRangeBetweenStartPosition:(CDStruct_912cb5d2)arg2 endPosition:(CDStruct_912cb5d2)arg3;
+ (CDStruct_912cb5d2)buffer:(id)arg1 locationOfNextString:(id)arg2 startingOnLine:(long long)arg3;

@end

