//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDESpriteKitParticleEditor/NSObject-Protocol.h>

@class GTFActionLibraryTargetThumbnail, NSString;
@protocol NSCopying;

@protocol GTFActionLibraryTarget <NSObject>
@property(readonly, nonatomic) NSString *gtf_name;
@property(readonly, nonatomic) GTFActionLibraryTargetThumbnail *gtf_thumbnailImage;
@property(readonly, nonatomic) id <NSCopying> gtf_uid;
@end

