//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <SpriteKit/SKScene.h>

@class GTFActionLibrary;

@interface SKScene (EditorAdditions)
@property(readonly, nonatomic) GTFActionLibrary *nav_actionLibrary;
- (void)setDocument:(id)arg1;
- (id)document;
- (void)sk_simulateToTime:(double)arg1;
- (id)sk_nodeToSelectAtPointIgnoringLocked:(struct CGPoint)arg1;
- (id)sk_nodeToSelectAtPoint:(struct CGPoint)arg1;
- (id)sk_nodeFromSecondaryNode:(id)arg1;
@end

