//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "SKInputViewDelegate.h"

@class NSMutableArray, NSString, SKScene;

@interface SKTileSetEditorView : NSView <SKInputViewDelegate>
{
    SKScene *_scene;
    NSMutableArray *_tileSets;
    id <SKTileSetEditorViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SKTileSetEditorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *tileSets; // @synthesize tileSets=_tileSets;
@property(retain, nonatomic) SKScene *scene; // @synthesize scene=_scene;
- (void).cxx_destruct;
- (void)frameDidChange:(id)arg1;
- (id)iconForImagePlaceholder;
- (void)drawRect:(struct CGRect)arg1;
- (void)inputView:(id)arg1 didPerformDragOperation:(id)arg2 atLocation:(struct CGPoint)arg3;
- (void)inputView:(id)arg1 draggingEntered:(id)arg2;
- (id)inputViewAcceptedDraggedTypes:(id)arg1;
- (void)inputView:(id)arg1 touchEnded:(unsigned long long)arg2 location:(struct CGPoint)arg3 clickCount:(int)arg4;
- (void)inputView:(id)arg1 touchMoved:(unsigned long long)arg2 location:(struct CGPoint)arg3 clickCount:(int)arg4;
- (void)inputView:(id)arg1 touchBegan:(unsigned long long)arg2 location:(struct CGPoint)arg3 clickCount:(int)arg4;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

