//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKTileDefinition.h"

@class NSArray;

@interface SKTileDefinition (InspectorAdditions)
+ (id)keyPathsForValuesAffectingInspectorTimePerFrameEnabled;
+ (id)keyPathsForValuesAffectingInspectorTextureFilenames;
@property(readonly, nonatomic) BOOL inspectorCannotRotateDefinition;
@property(readonly, nonatomic) BOOL inspectorCanRotateDefinition;
@property(readonly, nonatomic) BOOL inspectorTimePerFrameEnabled;
@property(nonatomic) BOOL inspectorFlipHorizontally;
@property(nonatomic) BOOL inspectorFlipVertically;
@property(nonatomic) unsigned long long inspectorRotation;
- (id)getTextureFilenames;
@property(retain, nonatomic) NSArray *inspectorTextureFilenames;
@end

