//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface Foundation._DataStorage : SwiftObject
{
    // Error parsing type: , name: _bytes
    // Error parsing type: , name: _length
    // Error parsing type: , name: _capacity
    // Error parsing type: , name: _needToZero
    // Error parsing type: , name: _deallocator
    // Error parsing type: , name: _backing
    // Error parsing type: , name: _offset
}

@end

