//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@interface Xcode3LocalizedSourceStringsAdaptorTargetWorkContext : IDELocalizationWorkContext
{
}

+ (id)contextWithParent:(id)arg1 target:(id)arg2 sourceFiles:(id)arg3;
- (id)mergedCommentsByTable;
- (id)mergedStringsByTable;
- (id)sourceFiles;
- (id)target;

@end

