//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTKPTrigger.h>

@class NSString;

@interface DTKPTriggerPMI : DTKPTrigger
{
    unsigned int _targetTask;
    NSString *_pmiEventNameOrAlias;
    unsigned long long _thresholdCount;
}

@property(readonly, nonatomic) unsigned long long thresholdCount; // @synthesize thresholdCount=_thresholdCount;
@property(readonly, retain, nonatomic) NSString *pmiEventNameOrAlias; // @synthesize pmiEventNameOrAlias=_pmiEventNameOrAlias;
@property(nonatomic) unsigned int targetTask; // @synthesize targetTask=_targetTask;
- (void).cxx_destruct;
- (int)stop:(id *)arg1;
- (int)start:(id *)arg1;
@property(readonly, nonatomic) unsigned long long pmcEventCount;
- (int)setPMIEventNamed:(id)arg1 threshold:(unsigned long long)arg2 error:(id *)arg3;
- (int)addPMCEventNamed:(id)arg1 error:(id *)arg2;
- (unsigned long long)_recordConfigWordsIntoBuffer:(unsigned long long *)arg1;

@end

