//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface DTPresentationSettingGroup : NSObject
{
    NSString *_groupName;
    NSArray *_settings;
}

@property(retain, nonatomic) NSArray *settings; // @synthesize settings=_settings;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (void).cxx_destruct;

@end

