//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTTapDataMemo.h>

@class NSArray;

@interface DTSysmonTapMemo : DTTapDataMemo
{
    NSArray *_samples;
}

@property(copy, nonatomic) NSArray *samples; // @synthesize samples=_samples;
- (void).cxx_destruct;

@end

