//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTTapMessageHandler.h>

@class NSData;

@interface DTSysmonTapMessageHandler : DTTapMessageHandler
{
    unsigned int _tapVersion;
    NSData *_nextSampleData;
}

- (void).cxx_destruct;
- (id)messageReceived:(id)arg1;

@end

