//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTTapMemo.h>

@interface DTTapDataMemo : DTTapMemo
{
    BOOL _supportsPeek;
    BOOL _finalMemo;
}

@property(nonatomic) BOOL finalMemo; // @synthesize finalMemo=_finalMemo;
@property(nonatomic) BOOL supportsPeek; // @synthesize supportsPeek=_supportsPeek;

@end

