//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class DVTPlistModel, DVTPlistNode, DVTPlistStructureDefinition;

@protocol DVTPlistDocumentProtocol
@property(retain) DVTPlistStructureDefinition *plistStructureDefinition;
- (BOOL)isReadOnly;
- (void)revealNode:(DVTPlistNode *)arg1;
- (void)propertyListChanged:(DVTPlistNode *)arg1;
- (DVTPlistModel *)model;
- (DVTPlistNode *)plist;
@end

