//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Xcode3UI/Xcode3FileBuildPhaseViewController.h>

@interface Xcode3EmbeddedBinariesPseudoPhaseViewcController : Xcode3FileBuildPhaseViewController
{
}

- (id)referencesToAddForContainerItems:(id)arg1;
- (void)filePickerView:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forTableColumn:(id)arg4 item:(id)arg5;
- (id)rootItemsForFilePickerPanel;
- (double)contentOriginXOffsetForCapsuleView:(id)arg1;
- (double)capsuleView:(id)arg1 preferredContentViewWidthForCapsuleWidth:(double)arg2;
- (BOOL)capsuleViewCanBeRemoved:(id)arg1;
- (BOOL)disclosedByDefault;
- (id)titleForDisplay;

@end

