//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEAssistantContext.h>

@class IDESourcePackageRequirement, NSString;

@interface Xcode3PackageAddPackageAssistantContext : IDEAssistantContext
{
    BOOL _hasValidRequirement;
    NSString *_repositoryURLString;
    IDESourcePackageRequirement *_requirement;
}

@property(nonatomic) BOOL hasValidRequirement; // @synthesize hasValidRequirement=_hasValidRequirement;
@property(copy, nonatomic) IDESourcePackageRequirement *requirement; // @synthesize requirement=_requirement;
@property(copy, nonatomic) NSString *repositoryURLString; // @synthesize repositoryURLString=_repositoryURLString;
- (void).cxx_destruct;

@end

