//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEKit/IDETemplateOptionsAssistant.h>

#import <Xcode3UI/IDETemplateTeamPickerViewControllerDelegate-Protocol.h>

@class IDETemplateTeamPickerViewController;

@interface Xcode3ProjectTemplateOptionsAssistant : IDETemplateOptionsAssistant <IDETemplateTeamPickerViewControllerDelegate>
{
    IDETemplateTeamPickerViewController *_teamPickerViewController;
}

- (void).cxx_destruct;
- (void)didSelectTeam:(id)arg1;
- (struct CGRect)_frameForControl:(id)arg1 option:(id)arg2 mainViewBounds:(struct CGRect)arg3 minLabelWidth:(double)arg4;
- (id)createControlForOption:(id)arg1 withOptionArray:(id)arg2;
- (id)additionalSortedOptions;
- (void)primitiveInvalidate;

@end

