//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSImage, PBXTarget;

@interface XCTargetSetting : NSObject
{
    PBXTarget *_target;
    NSArray *_fileRefs;
    long long _chosen;
    BOOL _validOption;
    BOOL _validRoleValues;
    NSImage *_image;
}

@property BOOL validRoleValues; // @synthesize validRoleValues=_validRoleValues;
@property BOOL validOption; // @synthesize validOption=_validOption;
- (void).cxx_destruct;
- (void)_removeObservers;
- (void)setRoleValue:(id)arg1;
- (id)roleValue;
- (void)setCapitalizedRoleValue:(id)arg1;
- (id)capitalizedRoleValue;
- (id)capitalizedRoleValues;
- (id)roleValues;
- (id)target;
- (long long)chosen;
- (void)setChosen:(long long)arg1;
- (void)setInitiallyChosen:(long long)arg1;
- (id)fileRefs;
- (void)computeChosen;
- (id)image;
- (id)initWithTarget:(id)arg1 fileRefs:(id)arg2 image:(id)arg3;

@end

