//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEQuickHelp/IDEQuickHelpQueryResult.h>

@class NSString;

@interface _TtC12IDEQuickHelp26IDEQuickHelpQueryDNTResult : IDEQuickHelpQueryResult
{
    // Error parsing type: , name: response
    // Error parsing type: , name: alternateDescription
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
- (void)reportToMessageTracer;
@property(nonatomic, readonly) NSString *abstract;

@end

