//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEFolderRootGroup.h>

__attribute__((visibility("hidden")))
@interface _TtC17IDESceneKitEditorP33_F5387E297C868E56B79F301C4C42A71B31_SKEAssetCatalogFolderRootGroup : IDEFolderRootGroup
{
}

- (id)init;
- (id)initWithPath:(id)arg1 resolutionStrategies:(id)arg2;
- (id)initWithName:(id)arg1;
- (id)allowedFileTypesOfChildItems;

@end

