//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDESceneKitEditor/IDECapsuleViewController-Protocol.h>
#import <IDESceneKitEditor/IDECapsuleViewDelegate-Protocol.h>

@class NSImage, NSString;

@interface SKEAssetCatalogCapsuleViewController : IDEViewController <IDECapsuleViewController, IDECapsuleViewDelegate>
{
}

@property(readonly) BOOL canDrag;
@property(readonly) BOOL canSelect;
- (id)capsuleViewBackgroundColor:(id)arg1;
@property(readonly) BOOL disclosedByDefault;
@property(readonly, copy) NSString *titleForDisplay;

// Remaining properties
@property BOOL canAddItems;
@property(readonly) BOOL canRemove;
@property BOOL canRemoveItems;
@property(readonly) BOOL canRename;
@property(readonly) BOOL canUndisclose;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *footerLabel;
@property(readonly) unsigned long long hash;
@property(readonly) NSImage *icon;
@property(readonly) Class superclass;

@end

