//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@class DVTObservingToken;
@protocol SKEDocumentMember, SKEDocumentProtocol;

@interface SKEDocumentNavigableItem : IDEKeyDrivenNavigableItem
{
    DVTObservingToken *_childMembersToken;
}

+ (id)keyPathsForValuesAffectingImage;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingRepresentedDocument;
+ (id)keyPathsForValuesAffectingRepresentedDocumentObject;
- (void).cxx_destruct;
- (id)contentDocumentLocation;
- (id)childRepresentedObjects;
- (BOOL)isLeaf;
- (unsigned long long)indexOfChildItemForIdentifier:(id)arg1;
- (id)identifierForChildItem:(id)arg1;
- (id)image;
- (id)name;
@property(readonly) __weak id <SKEDocumentProtocol> representedDocument;
@property(readonly) __weak id <SKEDocumentMember> representedDocumentObject;
- (void)primitiveInvalidate;
- (id)initWithRepresentedObject:(id)arg1;

@end

