//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SKEDocumentMemberFactory : NSObject
{
}

+ (id)material;
+ (id)dynamicBody;
+ (id)magneticField;
+ (id)electricField;
+ (id)springField;
+ (id)turbulenceField;
+ (id)noiseField;
+ (id)linearGravityField;
+ (id)radialGravityField;
+ (id)vortexField;
+ (id)dragField;
+ (id)particleSystem;
+ (id)text;
+ (id)floor;
+ (id)torus;
+ (id)capsule;
+ (id)tube;
+ (id)cone;
+ (id)cylinder;
+ (id)pyramid;
+ (id)geodesicSphere;
+ (id)sphere;
+ (id)box;
+ (id)plane;
+ (id)lightIES;
+ (id)lightProbe;
+ (id)ambientLight;
+ (id)spotLight;
+ (id)directionalLight;
+ (id)omniLight;
+ (id)camera;
+ (id)node;
+ (id)memberOfClass:(Class)arg1;

@end

