//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTViewController.h"

#import "SCNProgramDelegate.h"

@class NSString, NSTextField, SCNGeometry, SCNMorpher, SCNView;

@interface SKEMorpherQuickLookViewController : DVTViewController <SCNProgramDelegate>
{
    SCNGeometry *_geometry;
    SCNMorpher *_morpher;
    SCNView *_sceneView;
    NSTextField *_nameTextField;
    unsigned long long _index;
}

- (void).cxx_destruct;
- (void)configureSceneView;
- (void)viewDidLoad;
- (id)sceneView;
- (id)initWithGeometry:(id)arg1 morpher:(id)arg2 andMorpherIndex:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

