//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDESceneKitEditor/SKEStaticTableViewInspector.h>

#import <IDESceneKitEditor/NSTableViewDataSource-Protocol.h>

@class DVTGradientImageButton, NSString;

@interface SKENodeConstraintsInspector : SKEStaticTableViewInspector <NSTableViewDataSource>
{
    DVTGradientImageButton *_deleteButton;
    DVTGradientImageButton *_addButton;
}

+ (id)tableColumnTitles;
+ (BOOL)wantsEditionBar;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)viewDidInstall;
- (void)loadView;
- (void)addConstraintAction:(id)arg1;
- (void)addAvoidOccluder:(id)arg1;
- (void)addSlider:(id)arg1;
- (void)addAcceleration:(id)arg1;
- (void)addReplicator:(id)arg1;
- (void)addDistance:(id)arg1;
- (void)addBillboard:(id)arg1;
- (void)addLookAt:(id)arg1;
- (void)deleteConstraintAction:(id)arg1;
- (void)configureEditionBar;
- (void)primitiveInvalidate;
- (void)didSetInspectedObjects:(id)arg1;
- (void)initViewData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

