//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCBuildSupportUI/IDECommandHandler-Protocol.h>
#import <XCBuildSupportUI/IDECommandHandlerVendor-Protocol.h>

@class NSString;

@interface IDEPIFDumpController : NSObject <IDECommandHandlerVendor, IDECommandHandler>
{
}

+ (id)handlerForAction:(SEL)arg1 withSelectionSource:(id)arg2;
+ (id)sharedInstance;
+ (void)initialize;
- (void)dumpPifForActiveWorkspace:(id)arg1;
- (void)_displayErrorMessage:(id)arg1 inWindow:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

