//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <XCTDaemonControl/XCTDaemonSession.h>

#import <XCTDaemonControl/XCTestManager_IDEInterface-Protocol.h>

@protocol XCTDaemonControlSessionDelegate;

@interface XCTDaemonControlSession : XCTDaemonSession <XCTestManager_IDEInterface>
{
}

- (id)_XCT_reportSelfDiagnosisIssue:(id)arg1 description:(id)arg2;
- (id)_XCT_logDebugMessage:(id)arg1;
- (id)_XCT_handleCrashReportData:(id)arg1 fromFileWithName:(id)arg2;
- (void)collectNewCrashReportsInDirectories:(id)arg1 matchingProcessNames:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)authorizeProcessWithIdentifier:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (id)proxyChannelForConnection:(id)arg1;

// Remaining properties
@property __weak id <XCTDaemonControlSessionDelegate> delegate; // @dynamic delegate;

@end

