//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#pragma mark Named Structures

struct CGLShareGroupRec;

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct ComponentInfo {
    unsigned int _field1;
    int _field2;
};

struct Context {
    struct _CGLContextObject *_field1;
    struct CGLShareGroupRec *_field2;
    struct __GLIContextRec *_field3;
    struct __GLIFunctionDispatchRec *_field4;
    struct __GLIFunctionDispatchRec *_field5;
};

struct FormatComponentsInfo {
    struct ComponentInfo _field1;
    struct ComponentInfo _field2;
    struct ComponentInfo _field3;
};

struct GLSLObject {
    unsigned int _field1;
};

struct ImageFormatInfo {
    unsigned int internalFormat;
    unsigned int format;
    unsigned int type;
};

struct ImageInfo {
    struct ImageFormatInfo clientFormatInfo;
    struct ImageFormatInfo engineFormatInfo;
    int width;
    int height;
    int depth;
    int compressed;
    int numSamples;
    int stride;
};

struct ImageRenderer {
    struct Context _field1;
    struct ImageInfo _field2;
    struct FormatComponentsInfo _field3;
    struct ImageFormatInfo _field4;
    struct shared_ptr<void> _field5;
    void *_field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned char _field9;
    struct GLSLObject _field10;
    unsigned int _field11;
    _Bool _field12;
    struct array<int, 16> _field13;
    struct {
        struct GLSLObject _field1;
        int _field2;
        int _field3;
        int _field4;
        int _field5;
    } _field14;
    struct PixelStoreState _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned int _field18;
};

struct PixelStoreState {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    int _field7;
    int _field8;
    unsigned char _field9;
    unsigned char _field10;
};

struct ToneMapRange {
    double min;
    double max;
};

struct _CGLContextObject;

struct __GLIFunctionDispatchRec;

struct array<int, 16> {
    int _field1[16];
};

struct shared_ptr<void> {
    void *_field1;
    struct __shared_weak_count *_field2;
};

