//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol IDEPlaygroundDeviceOwner
- (void)playgroundDeviceWithIdentifier:(NSString *)arg1 wasAssignedToOwner:(id <IDEPlaygroundDeviceOwner>)arg2;
- (void)playgroundDeviceWithIdentifier:(NSString *)arg1 wasRequestedBy:(id <IDEPlaygroundDeviceOwner>)arg2;
@end

