//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEModelEditor/IDEDataModelPropertiesTableController.h>

@class NSArray;

@interface IDEDataModelAttributesController : IDEDataModelPropertiesTableController
{
}

- (id)defaultTableColumnIdentifiersForTableView:(id)arg1;
- (id)allowedTableColumnIdentifiersForTableView:(id)arg1;
- (id)identifier;
- (void)removeItems:(id)arg1;
- (void)addItems:(id)arg1;
- (Class)targetedEditorClass;
- (id)titleForDisplay;
- (void)primitiveInvalidate;
@property(readonly, copy) NSArray *typeNames;

@end

