//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEModelEditor/IDEDMGeniusResultsFinder.h>

@interface IDEMappingModelGeniusResultsFinder : IDEDMGeniusResultsFinder
{
}

+ (Class)editorDocumentClass;
- (BOOL)_getUpdateGeniusResultsPhaseOneBlock:(CDUnknownBlockType *)arg1 phaseTwoBlock:(CDUnknownBlockType *)arg2 phaseThreeBlock:(CDUnknownBlockType *)arg3;
- (id)_geniusLocationsForMappingModelDocument:(id)arg1 withWorkspaceContainerQueryMatches:(id)arg2;
- (id)geniusQueryMatches;
- (id)_locationForURL:(id)arg1 inQueryResults:(id)arg2 matchOnlyLastComponent:(BOOL)arg3;
- (id)geniusCategoryIdentifier;

@end

