//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCSServicesManager.h"

@interface XCSServicesManager (IDE)
- (void)clearlastCreatedBotIDForService:(id)arg1;
- (void)removeService:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
@end

