//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <XCSCore/XCSServicesManager.h>

@interface XCSServicesManager (IDE)
- (void)postAlertsForIntegrationID:(id)arg1 service:(id)arg2;
- (void)clearlastCreatedBotIDForService:(id)arg1;
- (void)removeService:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
@end

