//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTViewController.h>

#import <XCSUI/NSOutlineViewDataSource-Protocol.h>
#import <XCSUI/NSOutlineViewDelegate-Protocol.h>
#import <XCSUI/XCSUIDataSourceSnapshotsObserver-Protocol.h>

@class DVTBorderedView, DVTOutlineView, DVTReplacementView, NSArray, NSScrollView, NSString, NSURL, XCSBuildResultSummary, XCSIntegration, XCSIntegrationIssues, XCSUIProgressReplacementView;

@interface XCSUIIntegrationSummaryViewController : DVTViewController <XCSUIDataSourceSnapshotsObserver, NSOutlineViewDelegate, NSOutlineViewDataSource>
{
    XCSIntegration *_integration;
    NSURL *_documentURL;
    NSArray *_selectedDocumentLocations;
    XCSUIProgressReplacementView *_issuesReplacementView;
    DVTReplacementView *_reflightOrProgressReplacementView;
    DVTReplacementView *_statusBadgesReplacementView;
    DVTReplacementView *_productsReplacementView;
    DVTReplacementView *_changesReplacementView;
    DVTReplacementView *_devicesReplacementView;
    DVTBorderedView *_borderedView;
    NSScrollView *_scrollView;
    DVTOutlineView *_summaryOutline;
    XCSIntegrationIssues *_issues;
    NSArray *_currentOutlineViewItems;
    XCSBuildResultSummary *_buildResultSummary;
}

@property(retain) XCSBuildResultSummary *buildResultSummary; // @synthesize buildResultSummary=_buildResultSummary;
@property(retain) NSArray *currentOutlineViewItems; // @synthesize currentOutlineViewItems=_currentOutlineViewItems;
@property(retain) XCSIntegrationIssues *issues; // @synthesize issues=_issues;
@property __weak DVTOutlineView *summaryOutline; // @synthesize summaryOutline=_summaryOutline;
@property __weak NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain) DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
@property __weak DVTReplacementView *devicesReplacementView; // @synthesize devicesReplacementView=_devicesReplacementView;
@property __weak DVTReplacementView *changesReplacementView; // @synthesize changesReplacementView=_changesReplacementView;
@property __weak DVTReplacementView *productsReplacementView; // @synthesize productsReplacementView=_productsReplacementView;
@property __weak DVTReplacementView *statusBadgesReplacementView; // @synthesize statusBadgesReplacementView=_statusBadgesReplacementView;
@property __weak DVTReplacementView *reflightOrProgressReplacementView; // @synthesize reflightOrProgressReplacementView=_reflightOrProgressReplacementView;
@property(retain) XCSUIProgressReplacementView *issuesReplacementView; // @synthesize issuesReplacementView=_issuesReplacementView;
@property(retain, nonatomic) NSArray *selectedDocumentLocations; // @synthesize selectedDocumentLocations=_selectedDocumentLocations;
@property(retain, nonatomic) NSURL *documentURL; // @synthesize documentURL=_documentURL;
@property(retain, nonatomic) XCSIntegration *integration; // @synthesize integration=_integration;
- (void).cxx_destruct;
- (id)statusString;
- (unsigned long long)warningCount;
- (unsigned long long)errorCount;
- (id)integrationTitle;
- (void)dataSource:(id)arg1 integrationStepChanged:(id)arg2 serviceSnapshot:(id)arg3 botSnapshot:(id)arg4 integrationSnapshot:(id)arg5;
- (void)sendReportDidLoadNotification;
- (void)configureIssuesInstalledReplacementView;
- (void)sizeChangesViewToFit;
- (BOOL)shouldUseStreamingLogsView;
- (id)changesViewController;
- (id)statusViewController;
- (id)streamingLogsViewController;
- (id)inflightViewController;
- (id)devicesViewController;
- (id)productsViewController;
- (id)issuesViewController;
- (void)_fetchIssuesAndUpdateViewsForIntegration:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineItems;
- (void)updateViewControllersWithIntegrationAndBuildResultSummary;
- (void)reloadOutline;
- (void)primitiveInvalidate;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

