//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEEditor.h>

#import <XCSUI/DVTReplacementViewDelegate-Protocol.h>

@class DVTObservingToken, DVTReplacementView, NSString, XCSCodeCoverageIntegration, XCSIntegration;

@interface XCSUIIntegrationReportEditor_Coverage : IDEEditor <DVTReplacementViewDelegate>
{
    DVTObservingToken *_reportObserver;
    XCSCodeCoverageIntegration *_coverageData;
    NSString *_reportType;
    XCSIntegration *_integration;
    DVTReplacementView *_replacementView;
}

@property __weak DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
@property(retain, nonatomic) XCSIntegration *integration; // @synthesize integration=_integration;
@property(retain, nonatomic) NSString *reportType; // @synthesize reportType=_reportType;
- (void).cxx_destruct;
- (void)coverageReportData:(CDUnknownBlockType)arg1;
- (id)reportDocument;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)primitiveInvalidate;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

