//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation40IDEStructureEditingMultiPlannedOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC13IDEFoundation47IDEStructureEditingAutoTargetInferenceOperation : _TtC13IDEFoundation40IDEStructureEditingMultiPlannedOperation
{
    // Error parsing type: , name: _shouldPromptForCopyMoveLeaveChoice
    // Error parsing type: , name: _needTargetSelection
    // Error parsing type: , name: _homogenousTargetSelection
    // Error parsing type: , name: _existingFileReference
    // Error parsing type: , name: _newReferencesCreated
    // Error parsing type: , name: referenceCreationCompletionBlock
}

- (CDUnknownBlockType).cxx_destruct;

@end

