//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTProvisioningProfileProvider-Protocol.h>

@class NSSet, NSString;

@interface IDEAbstractProvisioningProfileProvider : NSObject <DVTProvisioningProfileProvider>
{
    NSString *_identifier;
}

+ (id)provisioningProfilePathExtension;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithIdentifier:(id)arg1;
- (id)provisioningProfileFromFilePath:(id)arg1 error:(id *)arg2;
- (id)provisioningProfileFromData:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSSet *supportedPlatforms; // @dynamic supportedPlatforms;

@end

