//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEFoundation/IDEBatchFindFilePathPredicate.h>

@class NSString;

@interface IDEBatchFindAbstractOperatorOperandPredicate : IDEBatchFindFilePathPredicate
{
    long long _operatorValue;
    NSString *_operand;
}

+ (id)decodeFromPropertyListRepresentation:(id)arg1;
+ (id)operatorToString:(long long)arg1;
+ (long long)operatorFromString:(id)arg1;
@property(readonly) NSString *operand; // @synthesize operand=_operand;
@property(readonly) long long operatorValue; // @synthesize operatorValue=_operatorValue;
- (void).cxx_destruct;
- (id)propertyListRepresentation;
- (BOOL)isWorkspaceSpecific;
- (BOOL)isEqualToFilePathPredicateWithIdenticalClass:(id)arg1;
- (unsigned long long)hash;
- (id)initWithOperator:(long long)arg1 operand:(id)arg2;

@end

