//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IDEBatchFindTextFragmentIndexContentGroup : NSObject
{
    NSString *_groupName;
    NSArray *_orderedFilePaths;
}

@property(readonly) NSArray *orderedFilePaths; // @synthesize orderedFilePaths=_orderedFilePaths;
@property(readonly) NSString *groupName; // @synthesize groupName=_groupName;
- (void).cxx_destruct;
- (id)initWithGroupName:(id)arg1 orderedFilePaths:(id)arg2;

@end

