//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDEProvisionable-Protocol.h>

@class DVTLogAspect, DVTPlatform, IDEDistributionItem, IDEDistributionMethod, IDEDistributionProvisioningEntitlementsExpansion, IDEProfileSpecifier, NSArray, NSOrderedSet, NSString;
@protocol IDEProvisioningBasicTeam;

@interface IDEDistributionProvisionable : NSObject <IDEProvisionable>
{
    IDEDistributionProvisioningEntitlementsExpansion *_entitlementsExpansion;
    DVTPlatform *_platform;
    IDEDistributionItem *_distributionItem;
    NSString *_certificateSpecifier;
    IDEProfileSpecifier *_profileSpecifier;
    id <IDEProvisioningBasicTeam> _team;
    IDEDistributionMethod *_method;
    long long _provisioningStyle;
    NSArray *_entitlementsProcessors;
    DVTLogAspect *_logAspect;
}

@property(readonly, nonatomic) DVTLogAspect *logAspect; // @synthesize logAspect=_logAspect;
@property(readonly, nonatomic) NSArray *entitlementsProcessors; // @synthesize entitlementsProcessors=_entitlementsProcessors;
@property(readonly, nonatomic) long long provisioningStyle; // @synthesize provisioningStyle=_provisioningStyle;
@property(readonly, nonatomic) IDEDistributionMethod *method; // @synthesize method=_method;
@property(readonly, nonatomic) id <IDEProvisioningBasicTeam> team; // @synthesize team=_team;
@property(retain, nonatomic) IDEProfileSpecifier *profileSpecifier; // @synthesize profileSpecifier=_profileSpecifier;
@property(copy, nonatomic) NSString *certificateSpecifier; // @synthesize certificateSpecifier=_certificateSpecifier;
@property(readonly, nonatomic) IDEDistributionItem *distributionItem; // @synthesize distributionItem=_distributionItem;
- (void).cxx_destruct;
- (unsigned long long)entitlementsDestinationForConfigurationNamed:(id)arg1;
- (id)provisioningPurposeForConfigurationNamed:(id)arg1;
@property(readonly, nonatomic, getter=isInstallerPackage) BOOL installerPackage;
- (BOOL)allowSigningWithoutTeamSelectionForConfigurationNamed:(id)arg1;
- (BOOL)signingRequiresTeamForConfigurationNamed:(id)arg1;
- (void)noteProvisioningInputsChanged;
- (id)appIDFeaturesForConfigurationNamed:(id)arg1;
- (id)entitlementsExpansionForConfigurationNamed:(id)arg1;
- (id)entitlementsFilePathForConfigurationNamed:(id)arg1;
- (id)baseEntitlementsForConfigurationNamed:(id)arg1;
- (id)provisioningProfileSpecifierForConfigurationNamed:(id)arg1;
- (id)signingCertificateIdentifierForConfigurationNamed:(id)arg1;
- (id)bundleIdentifierForConfigurationNamed:(id)arg1;
- (id)platformForConfigurationNamed:(id)arg1;
- (long long)profileSupportForConfigurationNamed:(id)arg1;
- (id)teamForConfigurationNamed:(id)arg1;
- (long long)provisioningStyleForConfigurationNamed:(id)arg1;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSOrderedSet *configurations;
- (id)initWithDistributionItem:(id)arg1 team:(id)arg2 method:(id)arg3 provisioningStyle:(long long)arg4 entitlementsProcessors:(id)arg5 logAspect:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

