//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEFoundation/IDELocalizationWorkContext.h>

@class DVTFilePath, NSArray, NSNumber;

@interface IDELocalizationWorkSystemTask : IDELocalizationWorkContext
{
}

+ (id)contextWithParent:(id)arg1 launchPath:(id)arg2 arguments:(id)arg3;
- (id)signalStatus;
@property(readonly, copy) NSNumber *exitStatus;
@property(readonly, copy) NSArray *arguments;
@property(readonly, copy) DVTFilePath *launchPath;

@end

