//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEFoundation/IDEMockProvisioningUserAction.h>

@class NSArray;

@interface IDEMockProvisioningRevokeCertificatesUserAction : IDEMockProvisioningUserAction
{
    NSArray *_certificates;
}

+ (id)revokeCertificatesUserActionWithCertificates:(id)arg1 context:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *certificates;
- (id)initWithUserActionName:(id)arg1 certificates:(id)arg2;

@end

