//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTInvalidation-Protocol.h>

@class DVTDelayedInvocation, DVTNotificationToken, DVTPortalCertificate, DVTStackBacktrace, IDEManageCertificatesContext, IDEManageCertificatesItemCollection, NSError, NSSet, NSString;
@protocol OS_dispatch_queue;

@interface IDEManageCertificatesItemSource : NSObject <DVTInvalidation>
{
    unsigned int _currentGeneration;
    NSObject<OS_dispatch_queue> *_reloadQueue;
    DVTNotificationToken *_certManagerToken;
    DVTNotificationToken *_accountsToken;
    BOOL _finishedInitialScan;
    BOOL _refreshing;
    BOOL _ignoreUpdates;
    NSError *_currentError;
    DVTDelayedInvocation *_delayedUpdate;
    IDEManageCertificatesContext *_context;
    IDEManageCertificatesItemCollection *_itemCollection;
    DVTPortalCertificate *_newlyCreatedCertificate;
}

+ (void)_portalCertificatesWithSession:(id)arg1 context:(id)arg2 outPortalCertificates:(id *)arg3 outPortalErrors:(id *)arg4;
+ (void)initialize;
@property(nonatomic) BOOL ignoreUpdates; // @synthesize ignoreUpdates=_ignoreUpdates;
@property(retain, nonatomic) DVTPortalCertificate *newlyCreatedCertificate; // @synthesize newlyCreatedCertificate=_newlyCreatedCertificate;
@property(readonly, nonatomic) IDEManageCertificatesItemCollection *itemCollection; // @synthesize itemCollection=_itemCollection;
@property(retain, nonatomic) IDEManageCertificatesContext *context; // @synthesize context=_context;
@property(retain, nonatomic) DVTDelayedInvocation *delayedUpdate; // @synthesize delayedUpdate=_delayedUpdate;
@property(nonatomic) BOOL refreshing; // @synthesize refreshing=_refreshing;
@property(nonatomic) BOOL finishedInitialScan; // @synthesize finishedInitialScan=_finishedInitialScan;
@property(retain, nonatomic) NSError *currentError; // @synthesize currentError=_currentError;
- (void).cxx_destruct;
- (void)_updateItemsOnMainThreadWithSerialNumbers:(id)arg1 portalCertificates:(id)arg2 localCertificates:(id)arg3 error:(id)arg4 quickLocalOnlyUpdate:(BOOL)arg5;
- (void)_reloadDataWithNewCertificateOrNil:(id)arg1;
- (void)requestCertificateType:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)_reloadQueue;
- (BOOL)deleteItemFromKeychain:(id)arg1 error:(id *)arg2;
- (void)_setUpObservations;
@property(readonly, nonatomic) NSSet *items;
- (void)primitiveInvalidate;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

