//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol IDEOnDiskTestAssetPrunerFileSystem;

@interface IDEOnDiskTestAssetPruner : NSObject
{
    id <IDEOnDiskTestAssetPrunerFileSystem> _fileSystem;
}

+ (id)_attachmentsDirectoryInTestDirectory:(id)arg1;
@property(readonly) id <IDEOnDiskTestAssetPrunerFileSystem> fileSystem; // @synthesize fileSystem=_fileSystem;
- (void).cxx_destruct;
- (BOOL)_pruneOrphanedAttachmentsInTestDirectory:(id)arg1 withError:(id *)arg2;
- (BOOL)_pruneOldSummariesInTestDirectory:(id)arg1 withError:(id *)arg2;
- (BOOL)_pruneSummaryAtPath:(id)arg1 testDirectory:(id)arg2 withError:(id *)arg3;
- (BOOL)_visitAllAttachmentsInSummaryAtPath:(id)arg1 testDirectory:(id)arg2 withError:(id *)arg3 visitor:(CDUnknownBlockType)arg4;
- (void)_deleteAttachmentWithFileName:(id)arg1 testDirectory:(id)arg2;
- (id)_summariesToPruneInTestDirectory:(id)arg1 withError:(id *)arg2;
- (id)_allSummariesInTestDirectory:(id)arg1 withError:(id *)arg2;
- (id)_exploreDirectory:(id)arg1 withError:(id *)arg2;
- (BOOL)pruneTestDirectory:(id)arg1 error:(id *)arg2;
- (id)initWithFileSystem:(id)arg1;

@end

