//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTInvalidation-Protocol.h>

@class DVTDelayedInvocation, DVTStackBacktrace, IDEAppIDFeatureCoordinator, IDECapabilitiesContext, NSArray, NSString, Xcode3TargetBuildSettingsCoordinator, Xcode3TargetEntitlementsCoordinator, Xcode3TargetInfoPlistCoordinator, Xcode3TargetLinkedFrameworksCoordinator;
@protocol IDEFlightChecking, IDEProjectItem, IDEProjectItemModelEntitlementsCoordinator;

@interface IDEProjectItemModel : NSObject <DVTInvalidation>
{
    NSArray *_flightChecks;
    BOOL _needToPublish;
    id <IDEFlightChecking> _appIDFeatureFlightCheck;
    IDECapabilitiesContext *_targetCapabilitiesContext;
    id <IDEProjectItem> _item;
    DVTDelayedInvocation *_delayedUpdateInvocation;
}

+ (void)initialize;
+ (Class)projectItemModelFlightCheckContextProviderClass;
@property BOOL needToPublish; // @synthesize needToPublish=_needToPublish;
@property(readonly) DVTDelayedInvocation *delayedUpdateInvocation; // @synthesize delayedUpdateInvocation=_delayedUpdateInvocation;
@property(readonly) id <IDEProjectItem> item; // @synthesize item=_item;
@property(readonly) IDECapabilitiesContext *targetCapabilitiesContext; // @synthesize targetCapabilitiesContext=_targetCapabilitiesContext;
@property(readonly, nonatomic) NSArray *flightChecks; // @synthesize flightChecks=_flightChecks;
- (void).cxx_destruct;
- (BOOL)entitlementsContainsEntitlementKey;
@property(readonly) Xcode3TargetInfoPlistCoordinator *infoPlistCoordinator;
@property(readonly) Xcode3TargetLinkedFrameworksCoordinator *linkedFrameworksCoordinator;
@property(readonly) IDEAppIDFeatureCoordinator *appIDFeatureCoordinator;
@property(readonly) Xcode3TargetEntitlementsCoordinator<IDEProjectItemModelEntitlementsCoordinator> *entitlementsCoordinator;
@property(readonly) Xcode3TargetBuildSettingsCoordinator *buildSettingsCoordinator;
- (void)runFlightChecks;
@property(readonly) BOOL requiresAccountAndTeamSelection;
@property(readonly) BOOL isEnabledUsingEducatedGuess;
- (void)setEnabled:(BOOL)arg1 flightCheckContext:(id)arg2;
- (BOOL)isEnabledWithoutEducatedGuess;
@property(readonly, getter=isEnabled) BOOL enabled;
- (void)publishStateWithContext:(id)arg1;
- (void)modelWasDisabled;
- (void)modelWasEnabledWithContext:(id)arg1;
- (void)updateWithContext:(id)arg1;
- (void)targetCoordinatorsChanged:(id)arg1;
@property(readonly, nonatomic) id <IDEFlightChecking> appIDFeatureFlightCheck; // @synthesize appIDFeatureFlightCheck=_appIDFeatureFlightCheck;
- (void)primitiveInvalidate;
- (id)init;
- (id)initWithCapabilitiesContext:(id)arg1 item:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

