//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTFilePath;

@interface IDEPlaygroundSectionFileReference : NSObject
{
    long long _type;
    DVTFilePath *_filePath;
    DVTFilePath *_originalContentsFilePath;
}

@property(retain) DVTFilePath *originalContentsFilePath; // @synthesize originalContentsFilePath=_originalContentsFilePath;
@property(retain) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(long long)arg1 filePath:(id)arg2 originalContentsFilePath:(id)arg3;

@end

