//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTInvalidation-Protocol.h>
#import <IDEFoundation/IDEProvisioningUserActionDelegate-Protocol.h>

@class DVTDispatchLock, DVTStackBacktrace, IDEProvisioningLedgerEntry, IDEProvisioningRepairContext, IDEProvisioningUserAction, NSArray, NSError, NSString;
@protocol IDEProvisioningRepairDelegate, IDERepairable;

@interface IDEProvisioningRepair : NSObject <DVTInvalidation, IDEProvisioningUserActionDelegate>
{
    IDEProvisioningLedgerEntry *_ledgerEntry;
    DVTDispatchLock *_userActionLock;
    BOOL _wantsDiagnoseProblemLedgerEntry;
    BOOL _executing;
    IDEProvisioningUserAction *_userAction;
    id <IDEProvisioningRepairDelegate> _delegate;
    IDEProvisioningRepairContext *_context;
    NSArray *_steps;
    NSError *_error;
}

+ (void)initialize;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(getter=isExecuting) BOOL executing; // @synthesize executing=_executing;
@property(copy, nonatomic) NSArray *steps; // @synthesize steps=_steps;
@property(readonly, nonatomic) IDEProvisioningRepairContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) id <IDEProvisioningRepairDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)userAction:(id)arg1 didFailWithError:(id)arg2;
- (void)userActionDidFinish:(id)arg1;
- (void)userActionDidBegin:(id)arg1;
- (void)userActionWasAuthorized:(id)arg1;
- (void)_closeLedgerEntriesWithError:(id)arg1;
- (void)_waitOnUserAction:(id)arg1;
@property(retain, nonatomic) IDEProvisioningUserAction *userAction; // @synthesize userAction=_userAction;
@property(readonly, nonatomic, getter=isWaitingForUserAction) BOOL waitingForUserAction;
- (void)_repairDidFinishWithUserAction:(id)arg1 error:(id)arg2;
- (id)_executionDiagnosticLedgerEntry;
- (void)_executeSteps:(id)arg1;
- (void)execute;
- (void)primitiveInvalidate;
@property(readonly, nonatomic) id <IDERepairable> repairable;
@property(readonly, copy) NSString *description;
- (id)initWithDelegate:(id)arg1 context:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

