//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTAppIDFeatures, DVTPlatform, DVTPortalProfileType, DVTSigningCertificateManager, IDEQualifiableProfileQualification, NSArray, NSDictionary, NSError, NSSet, NSString;
@protocol DVTProvisioningProfile, IDEProvisioningBasicTeam;

@interface IDEProfileQualification : NSObject
{
    NSSet *_passed;
    NSSet *_failed;
    NSArray *_qualifiers;
    NSSet *_signingCertificates;
    NSError *_signingCertificatesCodesignResolverError;
    DVTAppIDFeatures *_features;
    NSDictionary *_entitlements;
    NSArray *_devices;
    DVTPortalProfileType *_profileType;
    DVTSigningCertificateManager *_signingCertificateManager;
    id <DVTProvisioningProfile> _profile;
    id <IDEProvisioningBasicTeam> _team;
    NSString *_bundleID;
    DVTPlatform *_platform;
    IDEQualifiableProfileQualification *_baseQualification;
}

+ (id)keyPathsForValuesAffectingAllowTeamProfiles;
@property(retain, nonatomic) IDEQualifiableProfileQualification *baseQualification; // @synthesize baseQualification=_baseQualification;
@property(readonly, nonatomic) DVTPlatform *platform; // @synthesize platform=_platform;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(readonly, nonatomic) id <IDEProvisioningBasicTeam> team; // @synthesize team=_team;
@property(readonly, nonatomic) id <DVTProvisioningProfile> profile; // @synthesize profile=_profile;
@property(retain, nonatomic) DVTSigningCertificateManager *signingCertificateManager; // @synthesize signingCertificateManager=_signingCertificateManager;
@property(retain, nonatomic) DVTPortalProfileType *profileType; // @synthesize profileType=_profileType;
@property(copy, nonatomic) NSArray *devices; // @synthesize devices=_devices;
@property(copy, nonatomic) NSDictionary *entitlements; // @synthesize entitlements=_entitlements;
@property(copy, nonatomic) DVTAppIDFeatures *features; // @synthesize features=_features;
@property(retain, nonatomic) NSError *signingCertificatesCodesignResolverError; // @synthesize signingCertificatesCodesignResolverError=_signingCertificatesCodesignResolverError;
@property(retain, nonatomic) NSSet *signingCertificates; // @synthesize signingCertificates=_signingCertificates;
@property(copy, nonatomic) NSArray *qualifiers; // @synthesize qualifiers=_qualifiers;
@property(copy, nonatomic) NSSet *failed; // @synthesize failed=_failed;
@property(copy, nonatomic) NSSet *passed; // @synthesize passed=_passed;
- (void).cxx_destruct;
- (id)_profileTypeQualifier;
- (id)_xcodeManagedQualifier;
- (id)_devicesQualifier;
- (id)_entitlementsQualifier;
- (id)_containerQualifierWithContainerName:(id)arg1 fetchBlock:(CDUnknownBlockType)arg2;
- (id)_featuresQualifier;
- (id)_signingCertificateInclusionQualifier:(BOOL)arg1;
- (id)signingCertificatesCodesignResolverErrorQualifierSubtitle;
- (id)_manualQualifiers;
- (id)_xcodeManagedQualifiers:(BOOL)arg1;
@property(readonly, nonatomic) NSArray *qualificationErrors;
- (id)_qualifiers;
@property(nonatomic) BOOL verboseErrors;
@property(nonatomic) BOOL allowTeamProfiles;
- (BOOL)isQualified;
- (BOOL)_qualifyWithQualifiers:(id)arg1;
- (BOOL)qualifyForManuallyManaged;
- (BOOL)qualifyForUseLocalAssets;
- (BOOL)qualifyForXcodeManaged;
- (BOOL)qualify;
- (id)initWithProfile:(id)arg1 team:(id)arg2 bundleID:(id)arg3 platform:(id)arg4;

@end

