//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTInvalidation.h"
#import "IDEProvisioningUserActionDelegate.h"

@class DVTDispatchLock, DVTStackBacktrace, IDEProvisioningLedgerEntry, IDEProvisioningRepairContext, IDEProvisioningUserAction, NSArray, NSError, NSString;

@interface IDEProvisioningRepair : NSObject <DVTInvalidation, IDEProvisioningUserActionDelegate>
{
    IDEProvisioningLedgerEntry *_ledgerEntry;
    DVTDispatchLock *_userActionLock;
    BOOL _wantsDiagnoseProblemLedgerEntry;
    BOOL _executing;
    IDEProvisioningUserAction *_userAction;
    id <IDEProvisioningRepairDelegate> _delegate;
    IDEProvisioningRepairContext *_context;
    NSArray *_steps;
    NSError *_error;
}

+ (void)initialize;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(getter=isExecuting) BOOL executing; // @synthesize executing=_executing;
@property(copy, nonatomic) NSArray *steps; // @synthesize steps=_steps;
@property(readonly, nonatomic) IDEProvisioningRepairContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) id <IDEProvisioningRepairDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)userAction:(id)arg1 didFailWithError:(id)arg2;
- (void)userActionDidFinish:(id)arg1;
- (void)userActionDidBegin:(id)arg1;
- (void)userActionWasAuthorized:(id)arg1;
- (void)_closeLedgerEntriesWithError:(id)arg1;
- (void)_clearUserActionAndInvalidate:(BOOL)arg1;
- (void)_waitOnUserAction:(id)arg1;
@property(retain, nonatomic) IDEProvisioningUserAction *userAction; // @synthesize userAction=_userAction;
@property(readonly, nonatomic, getter=isWaitingForUserAction) BOOL waitingForUserAction;
- (id)_executionDiagnosticLedgerEntry;
- (void)_executeSteps:(id)arg1;
- (void)execute;
- (void)primitiveInvalidate;
@property(readonly, nonatomic) id <IDERepairable> repairable;
@property(readonly, copy) NSString *description;
- (id)initWithDelegate:(id)arg1 context:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

