//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDETestApplicationDependencyMapper : NSObject
{
}

+ (id)bundleIdentifierForBundleAtURL:(id)arg1;
+ (id)_bundleIdentifierMapForApplicationsAtURLs:(id)arg1 error:(id *)arg2;
+ (id)_applicationsInDirectories:(id)arg1 error:(id *)arg2;
+ (id)bundleIdentifierMapWithDependentProductPaths:(id)arg1 searchDirectories:(id)arg2 error:(id *)arg3;

@end

