//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEIssueProvider;
@protocol IDEIssueLogDataSource;

@interface IDEWorkspaceIssueProviderContext : NSObject
{
    IDEIssueProvider *_issueProvider;
    id <IDEIssueLogDataSource> _dataSource;
    unsigned long long _hash;
}

@property(readonly) id <IDEIssueLogDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly) IDEIssueProvider *issueProvider; // @synthesize issueProvider=_issueProvider;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithIssueManager:(id)arg1 dataSource:(id)arg2;

@end

