//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOrderedSet;

@interface DVTProxiedDeviceSet : NSObject
{
    NSOrderedSet *_proxiedDevices;
    id <DVTBasicDevice> _activeProxiedDevice;
}

+ (id)proxiedDevicesSetWithDevices:(id)arg1 activeProxiedDevice:(id)arg2;
@property(readonly) id <DVTBasicDevice> activeProxiedDevice; // @synthesize activeProxiedDevice=_activeProxiedDevice;
@property(readonly) NSOrderedSet *proxiedDevices; // @synthesize proxiedDevices=_proxiedDevices;
- (void).cxx_destruct;

@end

