//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCSCore/XCSObject.h>

#import "XCSIssueAssociationType.h"

@class NSString;

@interface XCSAssigneeIssueAssociation : XCSObject <XCSIssueAssociationType>
{
    NSString *_username;
}

+ (id)assigneeIssueAssociationWithUsername:(id)arg1 validationErrors:(id *)arg2;
+ (id)associationKey;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;
- (id)saveRepresentation;
- (id)dictionaryRepresentation;
- (BOOL)_validateUsername:(id)arg1 validationErrors:(id *)arg2;
- (id)initWithContents:(id)arg1 service:(id)arg2 validationErrors:(id *)arg3;
- (id)initWithUsername:(id)arg1 validationErrors:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

