//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IBFoundation/IBICSlot.h>

@class IBICColorSpace, IBICIdiom;

@interface IBICColorSetRepSlot : IBICSlot
{
    IBICIdiom *_idiom;
    IBICColorSpace *_colorSpace;
}

+ (id)detailAreaGroupPathForIdiom:(id)arg1 colorSpace:(id)arg2;
+ (id)genesisSlotsForSlots:(id)arg1;
+ (id)slotWithIdiom:(id)arg1 colorSpace:(id)arg2;
+ (id)orderedComponentClasses;
+ (Class)assetRepClass;
+ (Class)assetSetClass;
+ (id)slotFilterWithIdiomFilter:(id)arg1 colorSpaceFilter:(id)arg2;
+ (id)slotFilterWithNilMatching:(long long)arg1 idioms:(id)arg2 colorSpaces:(id)arg3;
+ (id)slotFilterUnionedWithStandardUniversalCounterpart:(BOOL)arg1 idioms:(id)arg2 colorSpaces:(id)arg3;
@property(readonly) IBICColorSpace *colorSpace; // @synthesize colorSpace=_colorSpace;
@property(readonly) IBICIdiom *idiom; // @synthesize idiom=_idiom;
- (void).cxx_destruct;
- (id)detailAreaPath;
- (long long)compareDisplayOrder:(id)arg1;
- (id)shortDisplayName;
- (void)captureComponents;

@end

