//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEComparisonEditor.h"

#import "NSTouchBarDelegate.h"
#import "NSTouchBarProvider.h"

@class NSString, NSTouchBar;

@interface IDEComparisonEditor (DFRSupport) <NSTouchBarProvider, NSTouchBarDelegate>
- (id)comparisonEditorDFRController;
- (id)_modeActionItemWithIdentifier:(id)arg1;
- (id)_navigationItemWithIdentifier:(id)arg1;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (void)_registerForComparisonEditorModeChange;
- (id)_touchBarForComparisonSubmode;
- (id)_touchBarForComparisonEditor;
- (id)makeTouchBar;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly) NSTouchBar *touchBar;
@end

