//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DYDeviceInfo, DYGPUToolsVersionInfo, NSArray, NSError, NSString;

@interface DYDevice : NSObject
{
    DYDeviceInfo *_deviceInfo;
    struct dispatch_queue_s *_eventsQueue;
}

+ (id)replayerAppIdentifier;
+ (Class)controlStrategyClass;
+ (Class)deferredLaunchStrategyClass;
+ (Class)launchStrategyClass;
@property(readonly, nonatomic) struct dispatch_queue_s *eventsQueue; // @synthesize eventsQueue=_eventsQueue;
@property(readonly, retain, nonatomic) DYDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (void).cxx_destruct;
- (BOOL)supportsPlaybackOfCaptureWithInfo:(id)arg1 limitBackwardsCompatibility:(BOOL)arg2 isInternal:(BOOL)arg3;
- (BOOL)versionIsOlderThan:(id)arg1;
- (id)iconDataForApplicationIdentifiers:(id)arg1;
- (id)createTransport;
@property(readonly, retain, nonatomic) NSString *standardTitle;
@property(readonly, retain, nonatomic) NSArray *supportedGraphicsAPIInfos;
@property(readonly, nonatomic) CDStruct_fc1d2ed0 mainScreenDescriptor;
@property(readonly, retain, nonatomic) DYGPUToolsVersionInfo *gputoolsVersionInfo;
@property(readonly, nonatomic) NSError *gputoolsServiceAvailabilityError;
@property(readonly, nonatomic) BOOL gputoolsServiceAvailable;
@property(readonly, nonatomic) unsigned int nativePointerSize;
@property(readonly, retain, nonatomic) NSString *productType;
@property(readonly, retain, nonatomic) NSString *build;
@property(readonly, retain, nonatomic) NSString *version;
@property(readonly, retain, nonatomic) NSString *name;
@property(readonly, nonatomic) BOOL sharedPermanentIdentifier;
@property(readonly, retain, nonatomic) NSString *permanentIdentifier;
@property(readonly, nonatomic) unsigned long long runtimeIdentifier;
@property(readonly, nonatomic) int platform;
- (id)init;

@end

