//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <GPUDebuggerMTLSupport/DYTexture-Protocol.h>

@class NSString;

@protocol DYPMTLTexture <DYTexture>
- (unsigned int)elementCount;
- (NSString *)pixelFormatAsString;
- (NSString *)typeAsString;
- (BOOL)isLuminance;
- (BOOL)isColor;
- (BOOL)isStencil;
- (BOOL)isDepth;
- (BOOL)isPacked;
@end

