//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol DYPResourceItemFactory <NSObject>
- (void)populatePlaceholderItem:(id <DYPResourceItem>)arg1 objectID:(unsigned long long)arg2 stateMirrorObject:(const void *)arg3 containerID:(unsigned long long)arg4 identifier:(NSString *)arg5;
- (id <DYPResourceItem>)placeholderResourceItemWithGroup:(id <DYPResourceGroup>)arg1 type:(unsigned int)arg2 identifier:(NSString *)arg3;
- (id <DYPRawBytesResourceItem>)rawBytesItemWithGroup:(id <DYPResourceGroup>)arg1 bytesType:(unsigned long long)arg2 bindingIndex:(unsigned int)arg3 stateMirrorObject:(const void *)arg4 containerID:(unsigned long long)arg5 identifier:(NSString *)arg6;
- (id <DYPShaderItem>)shaderItemWithProgram:(id <DYPProgramItem>)arg1 shaderType:(unsigned int)arg2 functionInfo:(id <DYPFunctionInfo>)arg3 identifier:(NSString *)arg4;
- (id <DYPProgramItem>)programItemWithGroup:(id <DYPResourceGroup>)arg1 programType:(unsigned int)arg2 programID:(unsigned long long)arg3 stateMirrorObject:(const void *)arg4 containerID:(unsigned long long)arg5 identifier:(NSString *)arg6;
- (id <DYPResourceItem>)resourceItemWithGroup:(id <DYPResourceGroup>)arg1 type:(unsigned int)arg2 objectID:(unsigned long long)arg3 stateMirrorObject:(const void *)arg4 containerID:(unsigned long long)arg5 identifier:(NSString *)arg6;
@end

