//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC23DNTDocumentationSupport15FuzzyTitleIndex : SwiftObject
{
    // Error parsing type: , name: languageIndices
    // Error parsing type: , name: indexURL
    // Error parsing type: , name: isIndexingEnabled
    // Error parsing type: , name: logCategory
}

@end

