//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSLayoutConstraint;

@interface SourceEditor.(SourceEditorLineAnnotationDropdownBackground in _5B634B9DCDB55D6100C0DC388A389C27) : NSView
{
    // Error parsing type: , name: topConstraint
    // Error parsing type: , name: heightConstraint
    // Error parsing type: , name: backgroundColor
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, retain) NSColor *backgroundColor; // @synthesize backgroundColor;
- (void)viewDidChangeBackingProperties;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint;
@property(nonatomic, retain) NSLayoutConstraint *topConstraint; // @synthesize topConstraint;

@end

