//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface SourceEditor.SourceEditorLineData : SwiftObject
{
    // Error parsing type: , name: lineContentRange
    // Error parsing type: , name: lineTerminatorLength
    // Error parsing type: , name: placeholders
    // Error parsing type: , name: hidden
    // Error parsing type: , name: layer
    // Error parsing type: , name: auxViews
    // Error parsing type: , name: accessoryView
    // Error parsing type: , name: substitutionView
    // Error parsing type: , name: accessibilityElement
}

@end

