//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class CALayer, NSTrackingArea, _TtC12SourceEditor21SourceEditorLineLayer;

@interface SourceEditor.FoldableRegionContextView : NSView
{
    // Error parsing type: , name: prefixLayer
    // Error parsing type: , name: suffixLayer
    // Error parsing type: , name: ellipsisLayer
    // Error parsing type: , name: edgeLayer
    // Error parsing type: , name: borderLayer
    // Error parsing type: , name: range
    // Error parsing type: , name: foldingController
    // Error parsing type: , name: layoutManager
    // Error parsing type: , name: hasKeyboardFocus
    // Error parsing type: , name: animationProgress
    // Error parsing type: , name: preferredLayoutInset
    // Error parsing type: , name: allowsSelection
    // Error parsing type: , name: currentTrackingArea
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewWasDeselectedIn:(id)arg1;
- (void)viewWasSelectedIn:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateTrackingAreas;
@property(nonatomic, retain) NSTrackingArea *currentTrackingArea; // @synthesize currentTrackingArea;
- (void)resetCursorRects;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)updateLayerStates;
- (void)configureLayers;
@property(nonatomic, readonly) BOOL allowsSelection; // @synthesize allowsSelection;
@property(nonatomic, readonly) double preferredLayoutInset; // @synthesize preferredLayoutInset;
- (struct CGSize)preferredSizeWithConstrainedBy:(struct CGSize)arg1;
- (id)makeBackingLayer;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) double animationProgress; // @synthesize animationProgress;
@property(nonatomic, readonly) CALayer *borderLayer; // @synthesize borderLayer;
@property(nonatomic, readonly) CALayer *edgeLayer; // @synthesize edgeLayer;
@property(nonatomic, readonly) CALayer *ellipsisLayer; // @synthesize ellipsisLayer;
@property(nonatomic, retain) _TtC12SourceEditor21SourceEditorLineLayer *suffixLayer; // @synthesize suffixLayer;
@property(nonatomic, retain) _TtC12SourceEditor21SourceEditorLineLayer *prefixLayer; // @synthesize prefixLayer;

@end

