//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSAdministration/_TtC17XCSAdministration20AdministrationRecipe.h>

@class NSString;

@interface _TtC17XCSAdministration18RelocateDataRecipe : _TtC17XCSAdministration20AdministrationRecipe
{
    // Error parsing type: , name: destinationDataPath
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)plan;
- (id)initWithDestinationDataPath:(id)arg1;
@property(nonatomic, readonly) NSString *destinationDataPath; // @synthesize destinationDataPath;

@end

