//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DTGraphKit/DTMemoryGraphItem.h>

@interface DTMemoryGraphReferenceItem : DTMemoryGraphItem
{
    unsigned int _srcNode;
    unsigned int _edgeName;
    unsigned int _dstNode;
}

- (id)name;
@property(readonly, nonatomic) CDStruct_8b65991f referenceInfo;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) unsigned int destinationIdentifier;
@property(readonly, nonatomic) unsigned int sourceIdentifier;
- (unsigned int)identifier;
- (long long)itemKind;
- (id)initWithEdge:(unsigned int)arg1 src:(unsigned int)arg2 dst:(unsigned int)arg3 graphIndex:(id)arg4;

@end

