//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRFrameActivityManager.h"

@class DTResponsiveUIContext;

@interface DTResponsiveUISubframe : XRFrameActivityManager
{
    DTResponsiveUIContext *_context;
}

- (void).cxx_destruct;
- (id)initWithContext:(id)arg1;

@end

