//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTMemoryGraphObjectInstanceItem.h"

@interface DTMemoryGraphObjectInstanceItem (InspectorSupport)
- (id)classHierarchyForDisplay;
- (id)mallocZoneForDisplay;
- (BOOL)shouldDisplayMallocZone;
- (id)instanceSizeForDisplay;
- (BOOL)shouldDisplayInstanceSize;
- (id)kindForDisplay;
- (BOOL)shouldDisplayKind;
- (id)inferiorPointer;
- (id)representedObjectClassNameForDisplay;
@property(readonly) id <DBGObjectInstanceInspectorProvider><DBGClassHierarchyInspectorProvider><DBGBacktraceInspectorProvider> object;
- (id)ideModelObjectTypeIdentifier;
@end

