//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDENavigableItemDomainProvider.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject.h"
#import "XRMemoryGraphDebuggerDomainWorkspaceDelegate.h"

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, NSArray, NSImage, NSMutableArray, NSNull, NSString;

@interface XRMemoryGraphDebuggerDomainProvider : IDENavigableItemDomainProvider <IDEKeyDrivenNavigableItemRepresentedObject, XRMemoryGraphDebuggerDomainWorkspaceDelegate>
{
    NSMutableArray *_domainWorkspaces;
    NSMutableArray *_memoryGraphDebuggers;
}

+ (id)domainObjectsForURL:(id)arg1 forWorkspace:(id)arg2;
+ (id)domainObjectForWorkspace:(id)arg1;
+ (id)providerForWorkspace:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (void)domainWorkspaceDidStopObserving:(id)arg1;
- (void)domainWorkspaceDidRemoveMemoryGraphDebugger:(id)arg1;
- (void)domainWorkspaceDidAddMemoryGraphDebugger:(id)arg1;
- (id)_representedObjectsForDocumentURL:(id)arg1;
- (id)_currentLaunchSession;
- (id)_currentTabController;
@property(readonly) NSString *navigableItem_name;
- (void)setupObservationForWorkspace:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSArray *memoryGraphDebuggers; // @dynamic memoryGraphDebuggers;
@property(readonly) NSMutableArray *mutableMemoryGraphDebuggers; // @dynamic mutableMemoryGraphDebuggers;
@property(readonly) NSString *navigableItem_accessibleImageDescription;
@property(readonly) NSArray *navigableItem_additionalFilterMatchingText;
@property(readonly) NSArray *navigableItem_childRepresentedObjects;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSNull *navigableItem_filtered;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) BOOL navigableItem_missingReferencedContentIsImportant;
@property(readonly) BOOL navigableItem_referencedContentExists;
@property(readonly) NSString *navigableItem_subtitle;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

