//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEMemoryGraphDebugger/DVTStatefulObject-Protocol.h>
#import <IDEMemoryGraphDebugger/IDEDebuggingAdditionUIController-Protocol.h>
#import <IDEMemoryGraphDebugger/XRNavigatorExpansionManager-Protocol.h>

@class DVTExtension, DVTObservingToken, DVTStackBacktrace, DVTStateToken, IDEWorkspaceTabController, NSArray, NSMutableDictionary, NSString, XRMemoryGraphDebuggerAddition, XRMemoryGraphDebuggerIndex;

@interface XRMemoryGraphDebuggerAdditionUIController : NSObject <DVTStatefulObject, IDEDebuggingAdditionUIController, XRNavigatorExpansionManager>
{
    IDEWorkspaceTabController *_workspaceTabController;
    NSMutableDictionary *_savedNavigatorState;
    DVTObservingToken *_memoryGraphDebuggerObservationToken;
    DVTObservingToken *_debuggerStateObservingToken;
    BOOL _userHasRequestedMemoryGraphDebugging;
    BOOL _shouldAutoSwitchDebugNavigatorContentMode;
    BOOL _showsOnlyLeakedBlocks;
    BOOL _showsOnlyContentFromWorkspace;
    XRMemoryGraphDebuggerAddition *_debuggingAddition;
    NSString *_filterString;
    DVTExtension *_extension;
    XRMemoryGraphDebuggerIndex *_filteredIndex;
    DVTStateToken *_stateToken;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)keyPathsForValuesAffectingFilteredChildren;
+ (void)initialize;
@property(retain) DVTStateToken *stateToken; // @synthesize stateToken=_stateToken;
@property(copy, nonatomic) XRMemoryGraphDebuggerIndex *filteredIndex; // @synthesize filteredIndex=_filteredIndex;
@property(readonly) DVTExtension *extension; // @synthesize extension=_extension;
@property(copy, nonatomic) NSString *filterString; // @synthesize filterString=_filterString;
@property(nonatomic) BOOL showsOnlyContentFromWorkspace; // @synthesize showsOnlyContentFromWorkspace=_showsOnlyContentFromWorkspace;
@property(nonatomic) BOOL showsOnlyLeakedBlocks; // @synthesize showsOnlyLeakedBlocks=_showsOnlyLeakedBlocks;
@property(nonatomic) BOOL shouldAutoSwitchDebugNavigatorContentMode; // @synthesize shouldAutoSwitchDebugNavigatorContentMode=_shouldAutoSwitchDebugNavigatorContentMode;
@property(nonatomic) BOOL userHasRequestedMemoryGraphDebugging; // @synthesize userHasRequestedMemoryGraphDebugging=_userHasRequestedMemoryGraphDebugging;
@property(retain, nonatomic) XRMemoryGraphDebuggerAddition *debuggingAddition; // @synthesize debuggingAddition=_debuggingAddition;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (id)preferredDescendantForItem:(id)arg1;
- (void)exemptItem:(id)arg1 fromFilterAndReset:(BOOL)arg2;
- (void)_reapplyFilteringState;
@property(readonly, nonatomic) NSArray *filteredChildren;
- (void)applyInitialExpansion:(id)arg1 toItem:(id)arg2;
- (BOOL)restoreExpansionAndScrollState:(id)arg1;
- (void)saveExpansionAndScrollState:(id)arg1;
- (BOOL)willSelectItem:(id)arg1 inNavigatorOutlineView:(id)arg2;
- (id)initWithWorkspaceTabController:(id)arg1 withDebuggingAddition:(id)arg2 forExtension:(id)arg3;

// Remaining properties
@property(readonly) BOOL canRevertWithEmptyStateDictionary;
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

