//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBBinaryArchiving.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface IBOffsetWrapper : NSObject <NSCopying, NSCoding, IBBinaryArchiving>
{
    double _horizontal;
    double _vertical;
}

+ (id)offsetWrapperWithOffset:(CDStruct_c3b9c2ee)arg1;
+ (id)zeroOffset;
@property(readonly, copy) NSString *description;
- (CDStruct_c3b9c2ee)offsetValue;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithHorizontal:(double)arg1 vertical:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

