//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IBCocoaTouchToolFoundation/IBUISimulatedMetricChain.h>

@interface IBUISimulatedDeviceContextMetricChain : IBUISimulatedMetricChain
{
    long long _idiom;
    long long _orientation;
    long long _interfaceStyle;
    struct CGSize _screenSize;
}

+ (BOOL)canBeRootOfMetricChain;
@property(readonly, nonatomic) long long interfaceStyle; // @synthesize interfaceStyle=_interfaceStyle;
@property(readonly, nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) long long idiom; // @synthesize idiom=_idiom;
@property(readonly, nonatomic) struct CGSize screenSize; // @synthesize screenSize=_screenSize;
- (id)explicitWindowSize;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithScreenSize:(struct CGSize)arg1 idiom:(long long)arg2 orientation:(long long)arg3 interfaceStyle:(long long)arg4;

@end

