//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <GPURenderTargetEditor/GPUTextureScrollViewDelegate-Protocol.h>

@class DYOpenGLView, GPURenderJob, GPUTextureScrollView, NSClickGestureRecognizer, NSPressGestureRecognizer, NSString;
@protocol DYResource, GPURenderBufferViewStateCoordinationProtocol;

@interface GPURenderBufferView : NSView <GPUTextureScrollViewDelegate>
{
    DYOpenGLView *_renderView;
    GPUTextureScrollView *_scrollView;
    double _maxMagnification;
    NSPressGestureRecognizer *_loupeLongPressGestureRecognizer;
    NSClickGestureRecognizer *_loupeDeepClickGestureRecognizer;
    NSClickGestureRecognizer *_loupeThirdButtonGestureRecognizer;
    BOOL _flipAboutX;
    BOOL _flipAboutY;
    id <DYResource> _resource;
    GPURenderJob *_renderJob;
    NSString *_title;
    id <GPURenderBufferViewStateCoordinationProtocol> _coordinator;
    struct CGSize _titleSize;
}

@property(nonatomic) BOOL flipAboutY; // @synthesize flipAboutY=_flipAboutY;
@property(nonatomic) BOOL flipAboutX; // @synthesize flipAboutX=_flipAboutX;
@property(nonatomic) __weak id <GPURenderBufferViewStateCoordinationProtocol> coordinator; // @synthesize coordinator=_coordinator;
@property(nonatomic) struct CGSize titleSize; // @synthesize titleSize=_titleSize;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) GPURenderJob *renderJob; // @synthesize renderJob=_renderJob;
@property(retain, nonatomic) id <DYResource> resource; // @synthesize resource=_resource;
- (void).cxx_destruct;
- (void)dumpImage:(id)arg1 asRaw:(BOOL)arg2;
- (void)_refreshScrollView;
- (struct CGRect)imageRectScreen;
- (void)synchronizeWithView:(id)arg1;
- (void)draw;
- (void)scrollViewDidScrollOrMagnify:(id)arg1;
- (void)hideLoupe;
- (void)showLoupeAtPosition:(struct CGPoint)arg1 makeFirstResponder:(BOOL)arg2;
- (void)_loupeViewGesture:(id)arg1;
@property(nonatomic) struct CGPoint loupePosition;
@property(readonly, nonatomic) BOOL isLoupeVisible;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)setScaleToFit;
@property(nonatomic) double scale;
@property(readonly, nonatomic) double maximumScale;
@property(readonly, nonatomic) double minimumScale;
@property(readonly, nonatomic) struct CGRect visibleResourceRect;
@property(readonly, nonatomic) struct CGSize resourceSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_GPURenderBufferViewInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

