//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GPUTracePipelineStatisticsDrawcallGraphView;

__attribute__((visibility("hidden")))
@interface GPUTracePipelineStatisticsDrawcallGraphCell : NSTableCellView
{
    GPUTracePipelineStatisticsDrawcallGraphView *_graph;
}

@property __weak GPUTracePipelineStatisticsDrawcallGraphView *graph; // @synthesize graph=_graph;
- (void).cxx_destruct;

@end

