//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <IDEKit/IDEIndexGeniusResult.h>

@class DVTDocumentLocation;

@interface IDEPegasusSourceEditor.(SourceCodeTestClassGeniusResult in _25CE0C9BBF1DA229A87429291B734721) : IDEIndexGeniusResult
{
}

- (id)init;
- (id)initWithIndexSymbol:(id)arg1;
@property(nonatomic, readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;

@end

