//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class NSNumber;

@protocol IDESourceKitRenameRange
@property(nonatomic, readonly) long long endColumn;
@property(nonatomic, readonly) long long endLine;
@property(nonatomic, readonly) long long column;
@property(nonatomic, readonly) long long line;
@property(nonatomic, readonly) NSNumber *argIndex;
@property(nonatomic, readonly) unsigned long long kind;
@end

