//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2018 08:38:15).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUTools/DYInOrderInstructionFilesVisitor.h>

@protocol DYCaptureStore;

__attribute__((visibility("hidden")))
@interface DYPlaybackEngineFSEBuilder : DYInOrderInstructionFilesVisitor
{
    struct PlaybackEngineDecodeCache *_cache;
    id <DYCaptureStore> _store;
    _Bool _buildDecodedFunctionStreams;
}

- (void)performPostCaptureVisitActions;
- (void)performPreCaptureVisitActions;
- (void)performPreVisitActions;
- (void)visitFunctionStreamFile:(id)arg1;
- (void)visitCaptureStore:(id)arg1;
- (id)initWithPlaybackEngineCache:(struct PlaybackEngineDecodeCache *)arg1;
- (id)init;

@end

